"""The module provides several palettes that are recomended to be used with plotting functions offered by Allos."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/000_palettes.ipynb.

# %% auto 0
__all__ = ['synthwave', 'ghibli']

# %% ../nbs/000_palettes.ipynb 3
synthwave = ['#100856', '#7243ee', '#da2ad3', '#3a58a4', '#2d149e', '#7f0d9a', '#3b0554', '#7a97f4', '#a127b4', '#696e43', '#de62e2', '#4e1af5', '#88904e', '#2d2c18', '#576d5c', '#4a4f20', '#909cfa', '#929574', '#c905ca', '#71a493']
ghibli = ['#6c6246', '#387041', '#153c27', '#393525', '#b19c77', '#175934', '#d0e7f3', '#466175', '#8c8c5a', '#47462c', '#8c414e', '#579f4e', '#7cb282', '#30363a', '#672c37', '#e5c6ad', '#402b2f', '#b0606e', '#c1e5d8', '#829ea7']
