"""This module provides tools to identify potential isoform switches within single-cell isoform-resolution datasets. It includes methods based on Dirichlet distributions and Wilcoxon tests for detecting differential isoform usage. These approaches are still under development and intended for exploratory use, with manual confirmation of detected isoform switches being essential."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/005_switch_search.ipynb.

# %% auto 0
__all__ = ['safe_sum', 'build_isoform_metrics_table', 'build_gene_metrics_table', 'SwitchSearch',
           'filter_sample_replicated_transcripts', 'compute_as_similarity', 'get_top_n_isoforms', 'plot_as_similarity',
           'plot_as_similarity_ordered']

# %% ../nbs/005_switch_search.ipynb 3
import anndata as ad

# %% ../nbs/005_switch_search.ipynb 4
from scipy.sparse import issparse, diags
from scipy.stats import chi2_contingency
from statsmodels.stats.multitest import multipletests
from collections import defaultdict
import numpy as np
import pandas as pd
import itertools
from joblib import Parallel, delayed
import warnings
import anndata
from .preprocessing import get_sot_gene_matrix
def safe_sum(X):
    # Handles both sparse and dense matrices robustly
    if issparse(X):
        # .A1 is only available for 1D sparse matrices; use .toarray().ravel() for generality
        return np.asarray(X.sum(axis=0)).ravel()
    else:
        return np.asarray(X.sum(axis=0)).ravel()

def build_isoform_metrics_table(
    adata: "anndata.AnnData",
    group_column: str,
    condition_column: str = None,
    comparisons: list = None,
    group_vs_rest: bool = False,
    epsilon: float = 1e-6,
    n_jobs: int = -1
) -> pd.DataFrame:
    """
    Compare levels in `group_column` at isoform level.
    If group_vs_rest=True, compares each group vs. all other cells.
    Otherwise does pairwise (or custom `comparisons`).
    """
    ad = adata.copy()
    tx_ids = ad.var.index.values
    gene_ids = ad.var['geneId'].values
    gene2tx = defaultdict(list)
    for idx, g in enumerate(gene_ids):
        gene2tx[g].append(idx)
    gene2tx = {g: np.array(v, dtype=int) for g, v in gene2tx.items()}

    def safe_sum_inner(X):
        if issparse(X):
            return np.asarray(X.sum(axis=0)).ravel()
        else:
            return np.asarray(X.sum(axis=0)).ravel()

    tasks = []
    if condition_column is not None:
        primaries = sorted(ad.obs[group_column].unique())
        conds = sorted(ad.obs[condition_column].unique())
        for pg in primaries:
            base = ad.obs[group_column] == pg
            for c1, c2 in itertools.combinations(conds, 2):
                m1 = base & (ad.obs[condition_column] == c1)
                m2 = base & (ad.obs[condition_column] == c2)
                tasks.append((m1.values, m2.values, f"{pg}:{c1}", f"{pg}:{c2}"))
    else:
        groups = sorted(ad.obs[group_column].unique())
        if group_vs_rest:
            for g in groups:
                m1 = ad.obs[group_column] == g
                m2 = ~m1
                tasks.append((m1.values, m2.values, str(g), 'rest'))
        else:
            pairs = comparisons or itertools.combinations(groups, 2)
            for g1, g2 in pairs:
                m1 = ad.obs[group_column] == g1
                m2 = ad.obs[group_column] == g2
                tasks.append((m1.values, m2.values, str(g1), str(g2)))

    def process_one(m1, m2, lab1, lab2):
        A1, A2 = ad[m1], ad[m2]
        X1, X2 = A1.X, A2.X
        n1, n2 = A1.n_obs, A2.n_obs
        c1, c2 = safe_sum_inner(X1), safe_sum_inner(X2)
        mexpr1, mexpr2 = c1/n1, c2/n2
        if issparse(X1):
            # .A1 is only for 1D, so use .toarray() and ravel for generality
            p1 = (X1 > 0).mean(axis=0).A1*100 if hasattr((X1 > 0).mean(axis=0), "A1") else np.asarray((X1 > 0).mean(axis=0)).ravel()*100
            p2 = (X2 > 0).mean(axis=0).A1*100 if hasattr((X2 > 0).mean(axis=0), "A1") else np.asarray((X2 > 0).mean(axis=0)).ravel()*100
        else:
            p1 = (X1 > 0).sum(axis=0).ravel()/n1*100
            p2 = (X2 > 0).sum(axis=0).ravel()/n2*100

        out = defaultdict(list)
        for gene, idxs in gene2tx.items():
            M1 = X1[:, idxs]; M2 = X2[:, idxs]
            rs1 = np.asarray(M1.sum(axis=1)).ravel() + epsilon
            rs2 = np.asarray(M2.sum(axis=1)).ravel() + epsilon
            # diags expects 1D arrays
            D1 = diags(1.0/rs1)
            D2 = diags(1.0/rs2)
            # D1.dot(M1) is (cells x tx), sum(axis=0) is tx
            # For sparse, .A1 is only for 1D, so use .toarray().ravel()
            ps1_raw = D1.dot(M1).sum(axis=0)
            ps2_raw = D2.dot(M2).sum(axis=0)
            if issparse(ps1_raw):
                ps1 = np.asarray(ps1_raw).ravel()/n1
            else:
                ps1 = np.asarray(ps1_raw).ravel()/n1
            if issparse(ps2_raw):
                ps2 = np.asarray(ps2_raw).ravel()/n2
            else:
                ps2 = np.asarray(ps2_raw).ravel()/n2
            lfc = np.log((ps1+epsilon)/(ps2+epsilon))
            dpsi = ps1-ps2
            L = len(idxs)
            out['comparison'].extend([f"{lab1}__{lab2}"]*L)
            out['gene_id'].extend([gene]*L)
            out['transcript_id'].extend(tx_ids[idxs])
            out['group_1'].extend([lab1]*L)
            out['group_2'].extend([lab2]*L)
            out['count_group1'].extend(c1[idxs].tolist())
            out['count_group2'].extend(c2[idxs].tolist())
            out['mean_expr_group1'].extend(mexpr1[idxs].tolist())
            out['mean_expr_group2'].extend(mexpr2[idxs].tolist())
            out['percent_expr_group1'].extend(p1[idxs].tolist())
            out['percent_expr_group2'].extend(p2[idxs].tolist())
            out['avg_psi_group1'].extend(ps1.tolist())
            out['log_fc'].extend(lfc.tolist())
            out['delta_psi'].extend(dpsi.tolist())
            out['n_cells_group1'].extend([n1]*L)
            out['n_cells_group2'].extend([n2]*L)
            out['total_cells'].extend([n1+n2]*L)
            out['total_count'].extend((c1[idxs]+c2[idxs]).tolist())
        return pd.DataFrame(out)

    dfs = Parallel(n_jobs=n_jobs)(
        delayed(process_one)(m1, m2, l1, l2) for m1, m2, l1, l2 in tasks
    )
    return pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()


def build_gene_metrics_table(
    adata: "anndata.AnnData",
    group_column: str,
    condition_column: str = None,
    comparisons: list = None,
    group_vs_rest: bool = False,
    epsilon: float = 1e-6,
    n_jobs: int = -1
) -> pd.DataFrame:
    """
    Compare levels in `group_column` at gene level.
    If group_vs_rest=True, compares each group vs. all other cells.
    """
    adf = get_sot_gene_matrix(adata)
    if 'geneId' not in adf.var.columns:
        adf.var['geneId'] = adf.var.index

    def safe_sum_inner(X):
        if issparse(X):
            return np.asarray(X.sum(axis=0)).ravel()
        else:
            return np.asarray(X.sum(axis=0)).ravel()

    tasks = []
    groups = sorted(adf.obs[group_column].unique())
    if group_vs_rest:
        for g in groups:
            m1 = adf.obs[group_column] == g
            m2 = ~m1
            tasks.append((m1.values, m2.values, str(g), 'rest'))
    else:
        if condition_column is not None:
            prim, conds = sorted(adf.obs[group_column].unique()), sorted(adf.obs[condition_column].unique())
            for pg in prim:
                for c1, c2 in itertools.combinations(conds, 2):
                    m1 = (adf.obs[group_column] == pg) & (adf.obs[condition_column] == c1)
                    m2 = (adf.obs[group_column] == pg) & (adf.obs[condition_column] == c2)
                    tasks.append((m1.values, m2.values, f"{pg}:{c1}", f"{pg}:{c2}"))
        else:
            pairs = comparisons or itertools.combinations(groups, 2)
            for g1, g2 in pairs:
                m1 = adf.obs[group_column] == g1
                m2 = adf.obs[group_column] == g2
                tasks.append((m1.values, m2.values, str(g1), str(g2)))

    def proc(m1, m2, l1, l2):
        A1, A2 = adf[m1], adf[m2]
        X1, X2 = A1.X, A2.X
        n1, n2 = A1.n_obs, A2.n_obs
        c1, c2 = safe_sum_inner(X1), safe_sum_inner(X2)
        me1, me2 = c1/n1, c2/n2
        if issparse(X1):
            p1_raw = (X1 > 0).mean(axis=0)
            p2_raw = (X2 > 0).mean(axis=0)
            p1 = p1_raw.A1*100 if hasattr(p1_raw, "A1") else np.asarray(p1_raw).ravel()*100
            p2 = p2_raw.A1*100 if hasattr(p2_raw, "A1") else np.asarray(p2_raw).ravel()*100
        else:
            p1 = (X1 > 0).sum(axis=0).ravel()/n1*100
            p2 = (X2 > 0).sum(axis=0).ravel()/n2*100
        lfc = np.log((me1+epsilon)/(me2+epsilon))
        genes = adf.var.index.values
        tot = c1 + c2
        comp = f"{l1}__{l2}"
        return pd.DataFrame({
            'comparison': [comp]*len(genes),
            'gene_id': genes,
            'group_1': [l1]*len(genes),
            'group_2': [l2]*len(genes),
            'count_group1': c1,
            'count_group2': c2,
            'mean_expr_group1': me1,
            'mean_expr_group2': me2,
            'percent_expr_group1': p1,
            'percent_expr_group2': p2,
            'log_fc': lfc,
            'n_cells_group1': [n1]*len(genes),
            'n_cells_group2': [n2]*len(genes),
            'total_cells': [n1+n2]*len(genes),
            'total_count': tot
        })

    dfs = Parallel(n_jobs=n_jobs)(delayed(proc)(*t) for t in tasks)
    return pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()

# %% ../nbs/005_switch_search.ipynb 6
import warnings
import itertools
import os
from typing import Dict, List, Optional

import anndata as ad
import numpy as np
import pandas as pd
from joblib import Parallel, delayed
from numba import njit
from scipy.stats import chi2  # p‑value outside Numba
from scipy.sparse import issparse

# ---------------------------------------------------------------------------
# Utility helpers
# ---------------------------------------------------------------------------

def safe_sum(x):
    """Axis‑0 sum that works for dense and sparse matrices (returns 1‑D)."""
    if issparse(x):
        return np.asarray(x.sum(axis=0)).ravel()
    return x.sum(axis=0)

# 2 × k Chi‑square (statistic only) -------------------------------------------
@njit(cache=True)
def _chi2_stat(a: np.ndarray, b: np.ndarray):
    n1, n2 = a.sum(), b.sum()
    tot = n1 + n2
    exp1 = (a + b) * (n1 / tot)
    exp2 = (a + b) * (n2 / tot)
    chi2_val = ((a - exp1) ** 2 / exp1).sum() + ((b - exp2) ** 2 / exp2).sum()
    dof = a.size - 1
    return chi2_val, dof

# ---------------------------------------------------------------------------
# Main class
# ---------------------------------------------------------------------------

class SwitchSearch(ad.AnnData):
    """High‑performance isoform‑switch search (Chi²)."""

    # -------------------------------------------------------------------
    # Construction
    # -------------------------------------------------------------------

    def __init__(
        self,
        anndata_obj: ad.AnnData,
        n_jobs: int = -1,
        compute_metrics: bool = False,
        fast_mode: bool = True,
        group_column: str = "cell_type",
        condition_column: Optional[str] = None,
    ):
        super().__init__(anndata_obj.copy())
        self.n_jobs = os.cpu_count() if n_jobs in (-1, 0) else n_jobs
        self.fast_mode = fast_mode
        self.group_column = group_column
        self.condition_column = condition_column

        # guarantee transcriptId exists
        if "transcriptId" not in self.var.columns:
            self.var["transcriptId"] = self.var.index

        self.transcript_metrics: Optional[pd.DataFrame] = None
        self.gene_metrics_table: Optional[pd.DataFrame] = None
        if compute_metrics and not fast_mode:
            self._build_metrics(group_column)

    # -------------------------------------------------------------------
    # Metric helpers
    # -------------------------------------------------------------------

    def _build_metrics(self, group_column: str):
        """Compute transcript‑ and gene‑level metrics in advance."""
        try:
            from allos.preprocessing import get_sot_gene_matrix

            self.transcript_metrics = build_isoform_metrics_table(
                self,
                group_column=group_column,
                comparisons=None,
                epsilon=1e-6,
                n_jobs=self.n_jobs,
            )

            adata_gene = get_sot_gene_matrix(self)
            if "geneId" not in adata_gene.var.columns:
                adata_gene.var["geneId"] = adata_gene.var.index
            self.gene_metrics_table = build_gene_metrics_table(
                adata_gene,
                group_column=group_column,
                comparisons=None,
                epsilon=1e-6,
                n_jobs=self.n_jobs,
            )
        except Exception as e:
            warnings.warn(f"Metric pre‑compute failed: {e}")

    # -------------------------------------------------------------------
    # Internal helpers
    # -------------------------------------------------------------------

    def _filter_gene_idx(self, g1: str, g2: str, min_reads: int, cg: str) -> np.ndarray:
        """Return array indices of isoforms passing min‑read filter."""
        m1, m2 = (self.obs[cg] == g1).values, (self.obs[cg] == g2).values
        mask = (safe_sum(self.X[m1]) > min_reads) & (safe_sum(self.X[m2]) > min_reads)
        return np.flatnonzero(mask)

    def _merge_and_prune(
        self,
        base: pd.DataFrame,
        metrics: pd.DataFrame,
        drop_missing: bool,
    ) -> pd.DataFrame:
        """Merge `metrics` into `base` and optionally drop rows lacking metrics."""
        merged = base.merge(
            metrics,
            on=["gene_id", "group_1", "group_2"],
            how="left",
            suffixes=("", "_alt"),
        )

        # consolidate primary / alt columns
        meta_cols = {"gene_id", "group_1", "group_2"}
        metric_cols = [c for c in metrics.columns if c not in meta_cols]
        for col in metric_cols:
            alt = f"{col}_alt"
            if alt in merged.columns:
                if col in merged.columns:
                    merged[col] = merged[col].fillna(merged[alt])
                else:
                    merged[col] = merged[alt]
                merged.drop(columns=alt, inplace=True)

        if drop_missing and metric_cols:
            keep_cols = [c for c in metric_cols if c in merged.columns]
            merged = merged.dropna(subset=keep_cols, how="all")
        return merged

    # -------------------------------------------------------------------
    # Public API
    # -------------------------------------------------------------------

    def find_switching_isoforms_chi2(
        self,
        cell_group_column: str = "cell_type",
        min_reads: int = 30,
        min_fdr: float = 0.05,
        return_transcript_metrics: bool = False,
        drop_unmatched_metrics: bool = True,
        n_jobs: Optional[int] = None,
    ) -> pd.DataFrame:
        """Run Chi² screen and return genes with metrics (if available)."""

        n_jobs = n_jobs or self.n_jobs
        cg = cell_group_column

        # 1 — valid groups & pre‑aggregate isoform counts (boolean mask to ndarray!)
        cell_counts = self.obs[cg].value_counts()
        valid_groups = cell_counts[cell_counts >= min_reads].index.tolist()
        comparisons = list(itertools.combinations(valid_groups, 2))
        iso_counts: Dict[str, np.ndarray] = {
            g: safe_sum(self.X[(self.obs[cg] == g).values]) for g in valid_groups
        }

        # 2 — worker for each pair
        def _proc(g1: str, g2: str):
            idx = self._filter_gene_idx(g1, g2, min_reads, cg)
            if idx.size == 0:
                return []
            gene_ids = self.var["geneId"].values[idx]
            out: list[dict] = []
            for gene in np.unique(gene_ids):
                iso_idx = idx[gene_ids == gene]
                if iso_idx.size < 2:
                    continue
                a = iso_counts[g1][iso_idx].astype(np.float64)
                b = iso_counts[g2][iso_idx].astype(np.float64)
                stat, dof = _chi2_stat(a, b)
                out.append({
                    "gene_id": gene,
                    "group_1": g1,
                    "group_2": g2,
                    "chi2_stat": stat,
                    "p_value": chi2.sf(stat, dof),
                    "dof": dof,
                })
            return out

        results = Parallel(n_jobs=n_jobs, backend="threading", prefer="threads")(
            delayed(_proc)(g1, g2) for g1, g2 in comparisons
        )
        res_df = pd.DataFrame([row for sub in results for row in sub])
        if res_df.empty:
            return res_df

        # 3 — FDR
        from statsmodels.stats.multitest import multipletests
        res_df["adj_pval"] = multipletests(res_df["p_value"], method="fdr_bh")[1]
        res_df = res_df[res_df["adj_pval"] <= min_fdr].copy()
        if res_df.empty:
            return res_df

        # 4 — ensure transcript metrics for sig genes (fast‑mode)
        if self.fast_mode and self.transcript_metrics is None:
            sig_genes = res_df["gene_id"].unique()
            adata_sub = self[:, self.var["geneId"].isin(sig_genes)]
            try:
                self.transcript_metrics = build_isoform_metrics_table(
                    adata_sub,
                    group_column=cg,
                    comparisons=None,
                    epsilon=1e-6,
                    n_jobs=n_jobs,
                )
            except Exception as e:
                warnings.warn(f"Fast‑mode transcript metrics failed: {e}")

        # 5 — merge metrics
        if return_transcript_metrics and self.transcript_metrics is not None:
            tm = self.transcript_metrics
            filt = (
                tm["gene_id"].isin(res_df["gene_id"]) &
                ((tm["percent_expr_group1"] >= 0.2) | (tm["percent_expr_group2"] >= 0.2)) &
                (tm["total_count"] >= min_reads) &
                (tm["delta_psi"].abs() > 0.1)
            )
            base = res_df.copy()
            merged = self._merge_and_prune(base, tm.loc[filt], drop_unmatched_metrics)
            swapped = tm.loc[filt].rename(columns={"group_1": "group_2", "group_2": "group_1"})
            return self._merge_and_prune(merged, swapped, drop_unmatched_metrics)

        if self.gene_metrics_table is not None:
            gmt = self.gene_metrics_table
            base = res_df.copy()
            merged = self._merge_and_prune(base, gmt, drop_unmatched_metrics)
            gmt_sw = gmt.rename(columns={"group_1": "group_2", "group_2": "group_1"})
            return self._merge_and_prune(merged, gmt_sw, drop_unmatched_metrics)

        return res_df


# %% ../nbs/005_switch_search.ipynb 7
def filter_sample_replicated_transcripts(adata, sample_col='sample', min_samples=2, min_umi=1):
    """
    Filters out transcripts that are not detected above a minimum UMI threshold 
    in at least a specified number of samples (replicates).

    Parameters:
      adata: AnnData object containing transcript-level counts.
      sample_col: Column in adata.obs that identifies the replicate/sample.
      min_samples: Minimum number of samples in which the transcript must be expressed.
      min_umi: Minimum UMI count in a sample for the transcript to be considered "expressed".
    
    Returns:
      A new AnnData object containing only transcripts that replicate across samples.
    """
    # Get unique sample identifiers.
    samples = adata.obs[sample_col].unique()
    
    # Dictionary to count in how many samples each transcript is expressed.
    transcript_presence = {tx: 0 for tx in adata.var_names}
    
    # Loop through each sample, calculate transcript counts, and mark transcripts that pass the threshold.
    for sample in samples:
        sample_adata = adata[adata.obs[sample_col] == sample]
        # Use your safe_sum helper to support both sparse and dense matrices.
        counts = safe_sum(sample_adata.X)
        # Loop over transcripts: if count > min_umi, mark as present.
        for tx, count in zip(adata.var_names, counts):
            if count > min_umi:
                transcript_presence[tx] += 1
    
    # Select transcripts that are expressed in at least min_samples samples.
    transcripts_to_keep = [tx for tx, count in transcript_presence.items() if count >= min_samples]
    print(f"Filtering out {adata.n_vars - len(transcripts_to_keep)} transcripts that are sample-specific")
    
    # Return a new AnnData object with only the replicated transcripts.
    return adata[:, transcripts_to_keep].copy()





# %% ../nbs/005_switch_search.ipynb 15
import pandas as pd
from scipy.stats import spearmanr

def compute_as_similarity(
    adata: ad.AnnData,
    group_column: str,
    transcripts: list[str],
    epsilon: float = 1e-6,
) -> pd.DataFrame:
    """
    Compute an AS‐similarity matrix (Spearman ρ) between all levels of `group_column`,
    using the PSI values of `transcripts`.

    Parameters
    ----------
    adata
        An AnnData containing your transcript‐by‐cell counts.
    group_column
        Column in adata.obs defining your cell groups (e.g. “cell_type”).
    transcripts
        List of var_names (transcript IDs) to include in the calculation.
    epsilon
        Small pseudocount to avoid division by zero when computing PSI.

    Returns
    -------
    corr_df : DataFrame
        A square DataFrame indexed and columned by the unique values of `group_column`,
        where corr_df.loc[g1, g2] is the Spearman ρ between the average‐PSI vectors
        of group g1 and group g2.
    """
    # 1) get cell‐level PSI matrix: cells × transcripts
    psi_mat = compute_cell_level_psi(adata, transcripts, epsilon)  
    psi_df = pd.DataFrame(psi_mat, 
                          index=adata.obs_names, 
                          columns=transcripts)

    # 2) tack on the group label, then average PSI per group
    psi_df[group_column] = adata.obs[group_column].values
    group_avg = psi_df.groupby(group_column).mean()

    # 3) compute pairwise Spearman correlations between group‐average PSI vectors
    groups = group_avg.index
    corr = pd.DataFrame(index=groups, columns=groups, dtype=float)
    for g1 in groups:
        for g2 in groups:
            ρ, _ = spearmanr(group_avg.loc[g1], group_avg.loc[g2])
            corr.loc[g1, g2] = ρ

    return corr


# %% ../nbs/005_switch_search.ipynb 16
def get_top_n_isoforms(adata, gene_id, top_n=5, strip=False):
    """
    Get the top_n transcript IDs for a given gene based on overall average expression.

    Parameters:
    - adata: AnnData object containing transcript-level data.
    - gene_id: The gene ID to search for corresponding isoforms.
    - top_n: The number of top isoforms to return based on overall average expression.
    - strip: Boolean indicating whether to strip the dot and everything after from the ID.

    Returns:
    - A list of top_n transcript IDs.
    """
    # Identify isoforms for the given gene ID
    isoforms = adata.var[adata.var['geneId'] == gene_id].index
    if len(isoforms) == 0:
        print(f"No isoforms found for gene ID: {gene_id}")
        return []

    # Calculate the overall average expression for each isoform
    overall_expr = adata.to_df()[isoforms].mean()

    # Get the top_n isoforms by average expression
    top_isoforms = overall_expr.sort_values(ascending=False).head(top_n).index.tolist()

    # Strip the dot and everything after from the ID if strip is True
    if strip:
        top_isoforms = [isoform.split('.')[0] for isoform in top_isoforms]

    return top_isoforms

# %% ../nbs/005_switch_search.ipynb 19
import matplotlib.pyplot as plt
import numpy as np

def plot_as_similarity(sim, cmap='magma'):
    """
    Enhanced AS‐similarity heatmap with colorbar and a 'magma' colormap.
    Text labels switch to white/black for better contrast.
    """
    fig, ax = plt.subplots(figsize=(8, 8))
    cax = ax.matshow(sim.values, cmap=cmap)
    # add colorbar with label
    cb = fig.colorbar(cax, ax=ax, fraction=0.046, pad=0.04)
    cb.set_label("Spearman ρ", rotation=270, labelpad=15)

    labels = sim.index.tolist()
    ax.set_xticks(np.arange(len(labels)))
    ax.set_yticks(np.arange(len(labels)))
    ax.set_xticklabels(labels, rotation=90, fontsize=10)
    ax.set_yticklabels(labels, fontsize=10)

    # annotate with correlation values and switch text color for visibility
    for (i, j), val in np.ndenumerate(sim.values):
        color = 'white' if val < 0.5 else 'black'
        ax.text(j, i, f"{val:.2f}", ha='center', va='center', color=color, fontsize=8)

    ax.set_title("AS Similarity (Spearman ρ)", pad=20)
    plt.tight_layout()
    plt.show()


# %% ../nbs/005_switch_search.ipynb 20
import numpy as np
import matplotlib.pyplot as plt
from scipy.cluster import hierarchy
from scipy.spatial.distance import squareform

def plot_as_similarity_ordered(sim, cmap='plasma'):
    """
    Reorders sim by 1–ρ linkage (loose ordering) and then plots a heatmap.
    """
    # 1) build a proper symmetric distance matrix = 1 – ρ
    D = 1 - sim.values
    D = (D + D.T) / 2      # enforce exact symmetry
    np.fill_diagonal(D, 0) # zero diagonal

    # 2) get condensed form
    condensed = squareform(D)

    # 3) linkage & leaf order
    Z = hierarchy.linkage(condensed, method='complete')
    order = hierarchy.dendrogram(Z, no_plot=True)['leaves']

    # 4) reorder your matrix & labels
    labels = sim.index.tolist()
    M = sim.values[np.ix_(order, order)]
    L = [labels[i] for i in order]

    # 5) plot
    fig, ax = plt.subplots(figsize=(8, 8))
    im = ax.matshow(M, cmap=cmap)
    cb = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cb.set_label("Spearman ρ", rotation=270, labelpad=15)

    ax.set_xticks(np.arange(len(L)))
    ax.set_yticks(np.arange(len(L)))
    ax.set_xticklabels(L, rotation=90, fontsize=10)
    ax.set_yticklabels(L, fontsize=10)

    # annotate
    for i in range(len(L)):
        for j in range(len(L)):
            v = M[i, j]
            c = 'white' if v < 0.5 else 'black'
            ax.text(j, i, f"{v:.2f}", ha='center', va='center', color=c, fontsize=8)

    ax.set_title("AS Similarity (Spearman ρ) — loosely ordered", pad=20)
    plt.tight_layout()
    plt.show()

