"""This module provides tools to identify potential isoform switches within single-cell isoform-resolution datasets. It includes methods based on Dirichlet distributions and Wilcoxon tests for detecting differential isoform usage. These approaches are still under development and intended for exploratory use, with manual confirmation of detected isoform switches being essential."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/005_switch_search.ipynb.

# %% auto 0
__all__ = ['SEP', 'build_gene_metrics_table', 'build_isoform_metrics_table', 'SwitchSearch',
           'filter_sample_replicated_transcripts', 'compute_as_similarity', 'get_top_n_isoforms', 'plot_as_similarity',
           'plot_as_similarity_ordered']

# %% ../nbs/005_switch_search.ipynb 3
import anndata 
import pandas as pd
from .preprocessing import get_sot_gene_matrix

# %% ../nbs/005_switch_search.ipynb 4
def build_gene_metrics_table(
    adata: "anndata.AnnData",
    group_column: str,
    condition_column: str = None,
    comparisons: list = None,
    group_vs_rest: bool = False,
    epsilon: float = 1e-6,
    n_jobs: int = -1
) -> pd.DataFrame:
    """
    Compare levels in `group_column` at gene level.
    If group_vs_rest=True, compares each group vs. all other cells.
    """
    adf = get_sot_gene_matrix(adata)
    if 'geneId' not in adf.var.columns:
        adf.var['geneId'] = adf.var.index

    def safe_sum_inner(X):
        if issparse(X):
            return np.asarray(X.sum(axis=0)).ravel()
        else:
            return np.asarray(X.sum(axis=0)).ravel()

    tasks = []
    groups = sorted(adf.obs[group_column].unique())
    if group_vs_rest:
        for g in groups:
            m1 = adf.obs[group_column] == g
            m2 = ~m1
            tasks.append((m1.values, m2.values, str(g), 'rest'))
    else:
        if condition_column is not None:
            prim, conds = sorted(adf.obs[group_column].unique()), sorted(adf.obs[condition_column].unique())
            for pg in prim:
                for c1, c2 in itertools.combinations(conds, 2):
                    m1 = (adf.obs[group_column] == pg) & (adf.obs[condition_column] == c1)
                    m2 = (adf.obs[group_column] == pg) & (adf.obs[condition_column] == c2)
                    tasks.append((m1.values, m2.values, f"{pg}:{c1}", f"{pg}:{c2}"))
        else:
            pairs = comparisons or itertools.combinations(groups, 2)
            for g1, g2 in pairs:
                m1 = adf.obs[group_column] == g1
                m2 = adf.obs[group_column] == g2
                tasks.append((m1.values, m2.values, str(g1), str(g2)))

    def proc(m1, m2, l1, l2):
        A1, A2 = adf[m1], adf[m2]
        X1, X2 = A1.X, A2.X
        n1, n2 = A1.n_obs, A2.n_obs
        c1, c2 = safe_sum_inner(X1), safe_sum_inner(X2)
        me1, me2 = c1/n1, c2/n2
        if issparse(X1):
            p1_raw = (X1 > 0).mean(axis=0)
            p2_raw = (X2 > 0).mean(axis=0)
            p1 = p1_raw.A1*100 if hasattr(p1_raw, "A1") else np.asarray(p1_raw).ravel()*100
            p2 = p2_raw.A1*100 if hasattr(p2_raw, "A1") else np.asarray(p2_raw).ravel()*100
        else:
            p1 = (X1 > 0).sum(axis=0).ravel()/n1*100
            p2 = (X2 > 0).sum(axis=0).ravel()/n2*100
        lfc = np.log((me1+epsilon)/(me2+epsilon))
        genes = adf.var.index.values
        tot = c1 + c2
        comp = f"{l1}__{l2}"
        return pd.DataFrame({
            'comparison': [comp]*len(genes),
            'gene_id': genes,
            'group_1': [l1]*len(genes),
            'group_2': [l2]*len(genes),
            'count_group1': c1,
            'count_group2': c2,
            'mean_expr_group1': me1,
            'mean_expr_group2': me2,
            'percent_expr_group1': p1,
            'percent_expr_group2': p2,
            'log_fc': lfc,
            'n_cells_group1': [n1]*len(genes),
            'n_cells_group2': [n2]*len(genes),
            'total_cells': [n1+n2]*len(genes),
            'total_count': tot
        })

    dfs = Parallel(n_jobs=n_jobs)(delayed(proc)(*t) for t in tasks)
    return pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()

# %% ../nbs/005_switch_search.ipynb 5
import itertools, os, warnings
from collections import defaultdict
from typing import Dict, List, Optional, Sequence, Tuple, Union

import anndata as ad
import numpy as np
import pandas as pd
from joblib import Parallel, delayed
from scipy.sparse import issparse
from scipy.stats import chi2
from statsmodels.stats.multitest import multipletests

# -----------------------------------------------------------------------------
# Optional Numba helpers — falls back gracefully if missing
# -----------------------------------------------------------------------------
try:
    from numba import njit, prange  # type: ignore
    _NUMBA = True
except ModuleNotFoundError:  # pragma: no cover
    _NUMBA = False
    def njit(*_a, **_kw):
        def _decor(f): return f
        return _decor
    prange = range  # type: ignore

# -----------------------------------------------------------------------------
# Utility helpers
# -----------------------------------------------------------------------------
SEP = "|"  # separator for composite labels (unlikely to be in raw IDs)

def _safe_sum(x):
    """Axis‑0 sum that works for dense **and** sparse matrices (returns 1‑D)."""
    return np.asarray(x.sum(axis=0)).ravel()


def _make_group_key(df: pd.DataFrame, cols: Sequence[str]):
    """Given one or several obs column names *cols*, return a Series with a
    composite key `<col0>|<col1>|…>` for every row.

    Works whether *cols* is a list **or** a tuple (fixes KeyError when a tuple
    was passed to `DataFrame.__getitem__`).
    """
    # pandas accepts a *list* of column labels, not a tuple
    if isinstance(cols, tuple):
        cols = list(cols)
    if len(cols) == 1:
        return df[cols[0]].astype(str)
    return df[cols].astype(str).agg(SEP.join, axis=1)


@njit(cache=True)
def _chi2_stat(a: np.ndarray, b: np.ndarray):
    n1, n2 = a.sum(), b.sum()
    tot = n1 + n2
    exp1 = (a + b) * (n1 / tot)
    exp2 = (a + b) * (n2 / tot)
    stat = ((a - exp1) ** 2 / exp1).sum() + ((b - exp2) ** 2 / exp2).sum()
    return stat, a.size - 1

# -----------------------------------------------------------------------------
# Metric builders — unchanged logic except `group_vs_rest` flag is honoured
# -----------------------------------------------------------------------------

def build_isoform_metrics_table(
    adata: ad.AnnData,
    group_columns: Sequence[str] | str,
    *,
    comparisons: Sequence[Tuple[str, str]] | None = None,
    group_vs_rest: bool = False,
    epsilon: float = 1e-6,
    n_jobs: int = -1,
) -> pd.DataFrame:
    """Return transcript‑level metrics for each comparison requested."""
    if isinstance(group_columns, str):
        group_columns = [group_columns]
    ad = adata.copy()
    ad.obs["_grp"] = _make_group_key(ad.obs, group_columns)
    grp_col = "_grp"

    tx_ids = ad.var.index.values
    gene_ids = ad.var.get("geneId", ad.var.index)

    gene2tx: Dict[str, np.ndarray] = defaultdict(list)
    for idx, gid in enumerate(gene_ids):
        gene2tx[gid].append(idx)
    gene2tx = {g: np.asarray(v, dtype=int) for g, v in gene2tx.items()}

    groups = sorted(ad.obs[grp_col].unique())

    tasks: List[Tuple[np.ndarray, np.ndarray, str, str]] = []
    if group_vs_rest:
        for g in groups:
            m1 = ad.obs[grp_col] == g
            m2 = ~m1
            tasks.append((m1.values, m2.values, str(g), "rest"))
    else:
        for g1, g2 in (comparisons or itertools.combinations(groups, 2)):
            m1 = ad.obs[grp_col] == g1
            m2 = ad.obs[grp_col] == g2
            tasks.append((m1.values, m2.values, str(g1), str(g2)))

    def _worker(mask1, mask2, lab1, lab2):
        A1, A2 = ad[mask1], ad[mask2]
        X1, X2 = A1.X, A2.X
        n1, n2 = A1.n_obs, A2.n_obs

        c1, c2 = _safe_sum(X1), _safe_sum(X2)
        mexpr1, mexpr2 = c1 / n1, c2 / n2

        if issparse(X1):
            p1 = np.asarray((X1 > 0).mean(axis=0)).ravel() * 100
            p2 = np.asarray((X2 > 0).mean(axis=0)).ravel() * 100
        else:
            p1 = (X1 > 0).sum(axis=0).ravel() / n1 * 100
            p2 = (X2 > 0).sum(axis=0).ravel() / n2 * 100

        psi1_all = np.empty(tx_ids.size, dtype=np.float32)
        psi2_all = np.empty_like(psi1_all)
        dpsi = np.empty_like(psi1_all)
        lfc = np.empty_like(psi1_all)

        for idxs in gene2tx.values():
            M1, M2 = X1[:, idxs], X2[:, idxs]
            rs1 = np.asarray(M1.sum(axis=1)).ravel() + epsilon
            rs2 = np.asarray(M2.sum(axis=1)).ravel() + epsilon
            if issparse(M1):
                psi1 = np.asarray(M1.multiply(1 / rs1[:, None]).sum(axis=0)).ravel() / n1
                psi2 = np.asarray(M2.multiply(1 / rs2[:, None]).sum(axis=0)).ravel() / n2
            else:
                psi1 = (M1 * (1 / rs1)[:, None]).sum(axis=0) / n1
                psi2 = (M2 * (1 / rs2)[:, None]).sum(axis=0) / n2
            psi1_all[idxs] = psi1
            psi2_all[idxs] = psi2
        dpsi[:] = psi1_all - psi2_all
        lfc[:] = np.log((psi1_all + epsilon) / (psi2_all + epsilon))

        return pd.DataFrame({
            "comparison": f"{lab1}__{lab2}",
            "gene_id": gene_ids,
            "transcript_id": tx_ids,
            "group_1": lab1,
            "group_2": lab2,
            "count_group1": c1,
            "count_group2": c2,
            "mean_expr_group1": mexpr1,
            "mean_expr_group2": mexpr2,
            "percent_expr_group1": p1,
            "percent_expr_group2": p2,
            "avg_psi_group1": psi1_all,
            "log_fc": lfc,
            "delta_psi": dpsi,
            "n_cells_group1": n1,
            "n_cells_group2": n2,
            "total_cells": n1 + n2,
            "total_count": c1 + c2,
        })

    dfs = Parallel(n_jobs=n_jobs)(delayed(_worker)(*t) for t in tasks)
    return pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()

# -----------------------------------------------------------------------------
# SwitchSearch — now with *metric‑cache auto‑fill*
# -----------------------------------------------------------------------------
class SwitchSearch(ad.AnnData):
    """High‑performance isoform‑switch search supporting nested and 1‑vs‑rest
    designs *and* auto‑managed metric caches.

    A **metric cache** is tied to a *signature* consisting of:
    1. the tuple `group_columns`
    2. the boolean `group_vs_rest`

    Every time you call `find_switches_chi2`, the signature is checked. If it
    differs from the cache, metrics are cleared and rebuilt lazily to match the
    new design. This guarantees that metric rows always share the exact same
    composite labels (`group_1`, `group_2`) used in the χ² search.
    """
    def __init__(
        self,
        anndata_obj: ad.AnnData,
        *,
        group_columns: Sequence[str] | str = ("cell_type",),
        n_jobs: int = -1,
        fast_mode: bool = True,
        precompute_metrics: bool = False,
    ):
        super().__init__(anndata_obj.copy())
        # Metric‑cache signature (tuple(group_columns), group_vs_rest_flag)
        self._metric_signature: Optional[Tuple[Tuple[str, ...], bool]] = None
        self.n_jobs = os.cpu_count() if n_jobs in (-1, 0) else n_jobs
        if isinstance(group_columns, str):
            group_columns = [group_columns]
        self.group_columns = tuple(group_columns)
        self.fast_mode = fast_mode
        self.obs["_grp"] = _make_group_key(self.obs, self.group_columns)

        self.transcript_metrics: Optional[pd.DataFrame] = None
        if precompute_metrics and not fast_mode:
            self._build_metrics()

    # ------------------------------------------------------------------
    # internal helpers
    # ------------------------------------------------------------------
    def _build_metrics(self, *, group_vs_rest: bool):
        self.transcript_metrics = build_isoform_metrics_table(
            self,
            self.group_columns,
            group_vs_rest=group_vs_rest,
            n_jobs=self.n_jobs,
        )
        self._metric_signature = (self.group_columns, group_vs_rest)

    def _ensure_metrics(self, df: pd.DataFrame, *, group_vs_rest: bool, n_jobs: int):
        """Make sure metric cache contains all (gene, g1, g2) needed in *df*.
        If the cache was built with a *different* signature, clear and rebuild.
        """
        sig = (self.group_columns, group_vs_rest)
        if self._metric_signature != sig:
            # Signature mismatch ⟹ flush cache and rebuild from scratch lazily
            self.transcript_metrics = None
            self._metric_signature = None

        if self.transcript_metrics is None:
            # build only for genes present in df
            ad_sub = self[:, self.var["geneId"].isin(df["gene_id"].unique())]
            self.transcript_metrics = build_isoform_metrics_table(
                ad_sub,
                self.group_columns,
                group_vs_rest=group_vs_rest,
                n_jobs=n_jobs,
            )
            self._metric_signature = sig
            return

        # identify (gene, g1, g2) combos still missing
        key = ["gene_id", "group_1", "group_2"]
        need = pd.merge(df[key].drop_duplicates(),
                        self.transcript_metrics[key].drop_duplicates(),
                        on=key, how="left", indicator=True)
        need = need.query("_merge == 'left_only'").drop(columns="_merge")
        if need.empty:
            return

        # compute extra metrics just for missing combos' genes
        genes = need["gene_id"].unique()
        ad_sub = self[:, self.var["geneId"].isin(genes)]
        extra = build_isoform_metrics_table(
            ad_sub,
            self.group_columns,
            group_vs_rest=group_vs_rest,
            n_jobs=n_jobs,
        )
        self.transcript_metrics = (
            pd.concat([self.transcript_metrics, extra], ignore_index=True)
              .drop_duplicates(subset=["gene_id", "transcript_id", "group_1", "group_2"])
        )

        # figure out which (gene, g1, g2) triples are missing
        key_cols = ["gene_id", "group_1", "group_2"]
        missing = pd.merge(
            df[key_cols].drop_duplicates(),
            self.transcript_metrics[key_cols].drop_duplicates(),
            on=key_cols, how="left", indicator=True,
        ).query("_merge == 'left_only'").drop(columns="_merge")
        if missing.empty:
            return  # all good

        # compute only for missing genes (to save time/RAM)
        new_genes = missing["gene_id"].unique()
        ad_sub = self[:, self.var["geneId"].isin(new_genes)]
        extra = build_isoform_metrics_table(
            ad_sub,
            self.group_columns,
            group_vs_rest=group_vs_rest,
            n_jobs=n_jobs,
        )
        self.transcript_metrics = (
            pd.concat([self.transcript_metrics, extra], ignore_index=True)
              .drop_duplicates(subset=["gene_id", "transcript_id", "group_1", "group_2"])
        )

    # ------------------------------------------------------------------
    # public API — χ² screen (nested, one‑vs‑rest, metric auto‑fill)
    # ------------------------------------------------------------------
    def find_switches_chi2(
        self,
        *,
        primary_col: Optional[str] = None,
        secondary_col: Optional[str] = None,
        within: str = "primary",
        group_vs_rest: bool = False,
        targets: Optional[Sequence[str]] = None,
        min_reads: int = 30,
        fdr: float = 0.05,
        return_transcript_metrics: bool = False,
        drop_unmatched_metrics: bool = True,
        n_jobs: Optional[int] = None,
    ) -> pd.DataFrame:
        n_jobs = n_jobs or self.n_jobs

        # ------- build composite label per cell ----------------------
        if secondary_col is None:
            group_key = self.obs[primary_col or self.group_columns[0]].astype(str)
        else:
            if primary_col is None:
                raise ValueError("`primary_col` must be provided when `secondary_col` is set.")
            group_key = _make_group_key(self.obs, [primary_col, secondary_col])
        uniq = group_key.unique().tolist()
        masks = {k: (group_key == k).values for k in uniq}
        iso_counts = {k: _safe_sum(self.X[m]) for k, m in masks.items()}

        # ------- decide comparison pairs -----------------------------
        if group_vs_rest:
            if targets is None:
                targets = uniq
            pairs = [(t, "rest") for t in targets if t in uniq]
        else:
            if secondary_col is None:
                pairs = list(itertools.combinations(sorted(uniq), 2))
            else:
                if within == "primary":
                    pairs = []
                    for p in self.obs[primary_col].unique():
                        ks = [k for k in uniq if k.split(SEP)[0] == str(p)]
                        pairs.extend(itertools.combinations(sorted(ks), 2))
                elif within == "secondary":
                    pairs = []
                    for s in self.obs[secondary_col].unique():
                        ks = [k for k in uniq if k.split(SEP)[1] == str(s)]
                        pairs.extend(itertools.combinations(sorted(ks), 2))
                elif within == "all":
                    pairs = list(itertools.combinations(sorted(uniq), 2))
                else:
                    raise ValueError("within must be 'primary', 'secondary', or 'all'.")

        # ------- χ² worker ------------------------------------------
        def _worker(k1: str, k2: str, b_counts: Optional[np.ndarray]):
            a = iso_counts[k1]
            b = b_counts if b_counts is not None else iso_counts[k2]
            valid = (a > min_reads) & (b > min_reads)
            if not valid.any():
                return []
            gene_ids = self.var["geneId"].values[valid]
            out = []
            for g in np.unique(gene_ids):
                idx = np.flatnonzero(gene_ids == g)
                if idx.size < 2:
                    continue
                stat, dof = _chi2_stat(a[valid][idx].astype(np.float64), b[valid][idx].astype(np.float64))
                out.append({
                    "gene_id": g,
                    "group_1": k1,
                    "group_2": k2,
                    "chi2_stat": stat,
                    "p_value": chi2.sf(stat, dof),
                    "dof": dof,
                })
            return out

        jobs = []
        for k1, k2 in pairs:
            if k2 == "rest":
                rest_counts = _safe_sum(self.X[~masks[k1]])
                jobs.append((k1, k2, rest_counts))
            else:
                jobs.append((k1, k2, None))

        results = Parallel(n_jobs=n_jobs, backend="threading", prefer="threads")(
            delayed(_worker)(k1, k2, c2) for k1, k2, c2 in jobs
        )
        df = pd.DataFrame([r for sub in results for r in sub])
        if df.empty:
            return df

        df["adj_pval"] = multipletests(df["p_value"], method="fdr_bh")[1]
        df = df[df["adj_pval"] <= fdr].copy()
        if df.empty:
            return df

        # ------- metric merge (auto‑fill missing) -------------------
        if return_transcript_metrics:
            self._ensure_metrics(df, group_vs_rest=group_vs_rest, n_jobs=n_jobs)
            tm = self.transcript_metrics
            filt = tm["gene_id"].isin(df["gene_id"])  # no per‑transcript read filter during merge
            df = df.merge(tm.loc[filt], on=["gene_id", "group_1", "group_2"], how="left")
            if not drop_unmatched_metrics:
                df = df.merge(
                    tm.loc[filt].rename(columns={"group_1": "group_2", "group_2": "group_1"}),
                    on=["gene_id", "group_1", "group_2"], how="left", suffixes=("", "_alt")
                )
        return df.reset_index(drop=True)



# %% ../nbs/005_switch_search.ipynb 9
def filter_sample_replicated_transcripts(adata, sample_col='sample', min_samples=2, min_umi=1):
    """
    Filters out transcripts that are not detected above a minimum UMI threshold 
    in at least a specified number of samples (replicates).

    Parameters:
      adata: AnnData object containing transcript-level counts.
      sample_col: Column in adata.obs that identifies the replicate/sample.
      min_samples: Minimum number of samples in which the transcript must be expressed.
      min_umi: Minimum UMI count in a sample for the transcript to be considered "expressed".
    
    Returns:
      A new AnnData object containing only transcripts that replicate across samples.
    """
    # Get unique sample identifiers.
    samples = adata.obs[sample_col].unique()
    
    # Dictionary to count in how many samples each transcript is expressed.
    transcript_presence = {tx: 0 for tx in adata.var_names}
    
    # Loop through each sample, calculate transcript counts, and mark transcripts that pass the threshold.
    for sample in samples:
        sample_adata = adata[adata.obs[sample_col] == sample]
        # Use your safe_sum helper to support both sparse and dense matrices.
        counts = safe_sum(sample_adata.X)
        # Loop over transcripts: if count > min_umi, mark as present.
        for tx, count in zip(adata.var_names, counts):
            if count > min_umi:
                transcript_presence[tx] += 1
    
    # Select transcripts that are expressed in at least min_samples samples.
    transcripts_to_keep = [tx for tx, count in transcript_presence.items() if count >= min_samples]
    print(f"Filtering out {adata.n_vars - len(transcripts_to_keep)} transcripts that are sample-specific")
    
    # Return a new AnnData object with only the replicated transcripts.
    return adata[:, transcripts_to_keep].copy()





# %% ../nbs/005_switch_search.ipynb 10
import pandas as pd
from scipy.stats import spearmanr

def compute_as_similarity(
    adata: ad.AnnData,
    group_column: str,
    transcripts: list[str],
    epsilon: float = 1e-6,
) -> pd.DataFrame:
    """
    Compute an AS‐similarity matrix (Spearman ρ) between all levels of `group_column`,
    using the PSI values of `transcripts`.

    Parameters
    ----------
    adata
        An AnnData containing your transcript‐by‐cell counts.
    group_column
        Column in adata.obs defining your cell groups (e.g. “cell_type”).
    transcripts
        List of var_names (transcript IDs) to include in the calculation.
    epsilon
        Small pseudocount to avoid division by zero when computing PSI.

    Returns
    -------
    corr_df : DataFrame
        A square DataFrame indexed and columned by the unique values of `group_column`,
        where corr_df.loc[g1, g2] is the Spearman ρ between the average‐PSI vectors
        of group g1 and group g2.
    """
    # 1) get cell‐level PSI matrix: cells × transcripts
    psi_mat = compute_cell_level_psi(adata, transcripts, epsilon)  
    psi_df = pd.DataFrame(psi_mat, 
                          index=adata.obs_names, 
                          columns=transcripts)

    # 2) tack on the group label, then average PSI per group
    psi_df[group_column] = adata.obs[group_column].values
    group_avg = psi_df.groupby(group_column).mean()

    # 3) compute pairwise Spearman correlations between group‐average PSI vectors
    groups = group_avg.index
    corr = pd.DataFrame(index=groups, columns=groups, dtype=float)
    for g1 in groups:
        for g2 in groups:
            ρ, _ = spearmanr(group_avg.loc[g1], group_avg.loc[g2])
            corr.loc[g1, g2] = ρ

    return corr


# %% ../nbs/005_switch_search.ipynb 11
def get_top_n_isoforms(adata, gene_id, top_n=5, strip=False):
    """
    Get the top_n transcript IDs for a given gene based on overall average expression.

    Parameters:
    - adata: AnnData object containing transcript-level data.
    - gene_id: The gene ID to search for corresponding isoforms.
    - top_n: The number of top isoforms to return based on overall average expression.
    - strip: Boolean indicating whether to strip the dot and everything after from the ID.

    Returns:
    - A list of top_n transcript IDs.
    """
    # Identify isoforms for the given gene ID
    isoforms = adata.var[adata.var['geneId'] == gene_id].index
    if len(isoforms) == 0:
        print(f"No isoforms found for gene ID: {gene_id}")
        return []

    # Calculate the overall average expression for each isoform
    overall_expr = adata.to_df()[isoforms].mean()

    # Get the top_n isoforms by average expression
    top_isoforms = overall_expr.sort_values(ascending=False).head(top_n).index.tolist()

    # Strip the dot and everything after from the ID if strip is True
    if strip:
        top_isoforms = [isoform.split('.')[0] for isoform in top_isoforms]

    return top_isoforms

# %% ../nbs/005_switch_search.ipynb 12
import matplotlib.pyplot as plt
import numpy as np

def plot_as_similarity(sim, cmap='magma'):
    """
    Enhanced AS‐similarity heatmap with colorbar and a 'magma' colormap.
    Text labels switch to white/black for better contrast.
    """
    fig, ax = plt.subplots(figsize=(8, 8))
    cax = ax.matshow(sim.values, cmap=cmap)
    # add colorbar with label
    cb = fig.colorbar(cax, ax=ax, fraction=0.046, pad=0.04)
    cb.set_label("Spearman ρ", rotation=270, labelpad=15)

    labels = sim.index.tolist()
    ax.set_xticks(np.arange(len(labels)))
    ax.set_yticks(np.arange(len(labels)))
    ax.set_xticklabels(labels, rotation=90, fontsize=10)
    ax.set_yticklabels(labels, fontsize=10)

    # annotate with correlation values and switch text color for visibility
    for (i, j), val in np.ndenumerate(sim.values):
        color = 'white' if val < 0.5 else 'black'
        ax.text(j, i, f"{val:.2f}", ha='center', va='center', color=color, fontsize=8)

    ax.set_title("AS Similarity (Spearman ρ)", pad=20)
    plt.tight_layout()
    plt.show()


# %% ../nbs/005_switch_search.ipynb 13
import numpy as np
import matplotlib.pyplot as plt
from scipy.cluster import hierarchy
from scipy.spatial.distance import squareform

def plot_as_similarity_ordered(sim, cmap='plasma'):
    """
    Reorders sim by 1–ρ linkage (loose ordering) and then plots a heatmap.
    """
    # 1) build a proper symmetric distance matrix = 1 – ρ
    D = 1 - sim.values
    D = (D + D.T) / 2      # enforce exact symmetry
    np.fill_diagonal(D, 0) # zero diagonal

    # 2) get condensed form
    condensed = squareform(D)

    # 3) linkage & leaf order
    Z = hierarchy.linkage(condensed, method='complete')
    order = hierarchy.dendrogram(Z, no_plot=True)['leaves']

    # 4) reorder your matrix & labels
    labels = sim.index.tolist()
    M = sim.values[np.ix_(order, order)]
    L = [labels[i] for i in order]

    # 5) plot
    fig, ax = plt.subplots(figsize=(8, 8))
    im = ax.matshow(M, cmap=cmap)
    cb = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cb.set_label("Spearman ρ", rotation=270, labelpad=15)

    ax.set_xticks(np.arange(len(L)))
    ax.set_yticks(np.arange(len(L)))
    ax.set_xticklabels(L, rotation=90, fontsize=10)
    ax.set_yticklabels(L, fontsize=10)

    # annotate
    for i in range(len(L)):
        for j in range(len(L)):
            v = M[i, j]
            c = 'white' if v < 0.5 else 'black'
            ax.text(j, i, f"{v:.2f}", ha='center', va='center', color=c, fontsize=8)

    ax.set_title("AS Similarity (Spearman ρ) — loosely ordered", pad=20)
    plt.tight_layout()
    plt.show()

