"""This module retrieves genomic coordinates and other key information related to transcripts from a GTF file. Using **pyRanges**, it efficiently stores and visualizes transcript features like exons, CDS, and UTRs.

Docs: https://cobioda.github.io/allostranscript_data.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/002_transcript_data.ipynb.

# %% ../nbs/002_transcript_data.ipynb #6f0fe828ba5c3d6f
from __future__ import annotations
import pandas as pd
from typing import List, Tuple, Dict, Optional
from functools import lru_cache
import pyranges as pr
import pysam  # Use pysam instead of pyfaidx for 64-bit coordinate support
import logging
import re
from typing import Any, Dict, Union


# %% auto #0
__all__ = ['CODON_TABLE', 'CheckOverlap', 'SmoothEnds', 'BuildSpliceGraph', 'FindBubbles', 'ClassifyBubble', 'TxRecord',
           'TranscriptIndex', 'classify_transcript_pair_from_index', 'TranscriptData', 'register_transcripts',
           'get_transcript_data', 'gene_junctions_df', 'gene_junctions_bed12', 'write_gene_junctions_bed12',
           'gene_junctions_bed6', 'classify_gene_junctions', 'isoform_specific_junctions',
           'choose_transcript_sentinels', 'read_regtools_bed12', 'match_counts_to_unique',
           'isoform_specific_among_expressed']

# %% ../nbs/002_transcript_data.ipynb #c4a30845
from networkx import all_simple_paths, get_node_attributes, DiGraph

def CheckOverlap(tuple1, tuple2):
    # Checks if tuple1 overlaps with tuple2
    return max(tuple1[0], tuple2[0]) <= min(tuple1[1], tuple2[1])

def SmoothEnds(inputDF):
    """
    Same as Wang's SmoothEnds but operates on our small 2-row DataFrame:
    columns: ['transcript_ID','chrom','strand','exonStart','exonEnd']
    """
    from numpy import sort

    copyDF = inputDF.copy()

    firstExon1 = (inputDF['exonStart'].iloc[0][0], inputDF['exonEnd'].iloc[0][0])
    firstExon2 = (inputDF['exonStart'].iloc[1][0], inputDF['exonEnd'].iloc[1][0])
    lastExon1  = (inputDF['exonStart'].iloc[0][-1], inputDF['exonEnd'].iloc[0][-1])
    lastExon2  = (inputDF['exonStart'].iloc[1][-1], inputDF['exonEnd'].iloc[1][-1])

    # start
    if firstExon1 != firstExon2:
        if CheckOverlap(sort(firstExon1), sort(firstExon2)):
            copyDF['exonStart'].iloc[1][0] = copyDF['exonStart'].iloc[0][0]

    # end
    if lastExon1 != lastExon2:
        if CheckOverlap(sort(lastExon1), sort(lastExon2)):
            copyDF['exonEnd'].iloc[1][-1] = copyDF['exonEnd'].iloc[0][-1]

    return copyDF

def BuildSpliceGraph(inputDF):
    # Establish an empty directed splice graph
    spliceGraph = DiGraph()

    # Establish a list of nodes for spliceGraph
    startNodes = [(V, {'attribute': 'start'}) for V in set(inputDF['exonStart'].sum())]
    endNodes   = [(V, {'attribute': 'end'})   for V in set(inputDF['exonEnd'].sum())]
    auxNodes   = [('sink', {'attribute': 'sink'}), ('root', {'attribute': 'root'})]

    # Establish a list of edges for spliceGraph
    exonEdges = list(set(sum(
        [list(zip(inputDF.iloc[idx]['exonStart'], inputDF.iloc[idx]['exonEnd']))
         for idx in range(inputDF.shape[0])], []
    )))
    intronEdges = list(set(sum(
        [list(zip(inputDF.iloc[idx]['exonEnd'][:-1], inputDF.iloc[idx]['exonStart'][1:]))
         for idx in range(inputDF.shape[0])], []
    )))
    auxEdges = list(set(sum(
        [[('root', inputDF.iloc[idx]['exonStart'][0]),
          (inputDF.iloc[idx]['exonEnd'][-1], 'sink')]
         for idx in range(inputDF.shape[0])], []
    )))

    spliceGraph.add_nodes_from(startNodes + endNodes + auxNodes)
    spliceGraph.add_edges_from(exonEdges + intronEdges + auxEdges)
    return spliceGraph

def FindBubbles(spliceGraph):
    """
    Same as Wang's FindBubbles – single pass from root to sink.
    """
    bubbles = []
    currentNode, bubbleStart = 'root', 'root'

    while not bubbleStart == 'sink':
        if spliceGraph.in_degree(currentNode) == 2:
            bubbles.append(list(all_simple_paths(spliceGraph,
                                                 source=bubbleStart,
                                                 target=currentNode)))

        if spliceGraph.out_degree(currentNode) == 2:
            bubbleStart = currentNode
            currentNode = list(spliceGraph.successors(currentNode))[0]
        elif spliceGraph.out_degree(currentNode) == 1:
            currentNode = list(spliceGraph.successors(currentNode))[0]
        else:
            bubbleStart = currentNode

    return bubbles

def ClassifyBubble(bubble, attributes):
    from numpy import sort

    path1, path2 = bubble

    if min(len(path1), len(path2)) == 2 and max(len(path1), len(path2)) == 4:
        if attributes[path1[0]] == 'start' and attributes[path1[-1]] == 'end':
            # intron retention
            return 'RI', ':'.join(list(map(str,
                sort(list(set(path1).symmetric_difference(set(path2)))) + [1, -1]
            )))
        elif attributes[path1[0]] == 'end' and attributes[path1[-1]] == 'start':
            # exon skipping
            return 'SE', ':'.join(list(map(str,
                sort(list(set(path1).symmetric_difference(set(path2))))
            )))
        else:
            return 'COMPLEX', 'NA'

    elif min(len(path1), len(path2)) == 3 and max(len(path1), len(path2)) == 3:
        if attributes[path1[0]] == 'start' and attributes[path1[-1]] == 'start':
            return 'A5SS', (
                ':'.join(list(map(str, sort(path1[:2])))) + ';' +
                ':'.join(list(map(str, sort(path2[:2]))))
            )
        elif attributes[path1[0]] == 'end' and attributes[path1[-1]] == 'end':
            return 'A3SS', (
                ':'.join(list(map(str, sort(path1[-2:])))) + ';' +
                ':'.join(list(map(str, sort(path2[-2:]))))
            )
        else:
            return 'COMPLEX', 'NA'

    elif min(len(path1), len(path2)) == 4 and max(len(path1), len(path2)) == 4:
        if (attributes[path1[0]] == 'end' and attributes[path1[-1]] == 'start' and
            not CheckOverlap(sort(path1[1:3]), sort(path2[1:3]))):
            return 'MXE', (
                ':'.join(list(map(str, sort(path1[1:3])))) + ';' +
                ':'.join(list(map(str, sort(path2[1:3]))))
            )
        elif (attributes[path1[0]] == 'root' and attributes[path1[-1]] == 'start' and
              not CheckOverlap(sort(path1[1:3]), sort(path2[1:3]))):
            return 'AFE', (
                ':'.join(list(map(str, sort(path1[1:3])))) + ';' +
                ':'.join(list(map(str, sort(path2[1:3]))))
            )
        elif (attributes[path1[0]] == 'end' and attributes[path1[-1]] == 'sink' and
              not CheckOverlap(sort(path1[1:3]), sort(path2[1:3]))):
            return 'ALE', (
                ':'.join(list(map(str, sort(path1[1:3])))) + ';' +
                ':'.join(list(map(str, sort(path2[1:3]))))
            )
        else:
            return 'COMPLEX', 'NA'
    else:
        return 'COMPLEX', 'NA'
    

# %% ../nbs/002_transcript_data.ipynb #initial_id
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple
import os, pathlib, pickle, hashlib, re
import numpy as np
import pandas as pd
import pyranges as pr

def _versionless(tid: str) -> str:
    """Strip version suffix from Ensembl IDs (e.g., ENST00000442987.3 -> ENST00000442987).
    
    Preserves PacBio IDs (PB.10.104) since the last number is the transcript ID, not a version.
    """
    # Don't strip PacBio IDs - the last number is the transcript ID, not a version
    if tid.startswith("PB."):
        return tid
    i = tid.rfind(".")
    return tid[:i] if i > 0 and tid[i + 1:].isdigit() else tid

@dataclass(frozen=True, slots=True)
class TxRecord:
    transcript_id: str
    gene_id: Optional[str]
    gene_name: Optional[str]
    transcript_name: Optional[str]
    transcript_type: Optional[str]
    chrom: str
    strand: int  # +1 / -1
    span: Tuple[int, int]  # (min_start, max_end)
    exons: np.ndarray      # (n,2) int32 [[Start,End],...]
    cds: np.ndarray
    utr5: np.ndarray
    utr3: np.ndarray

    @property
    def junctions(self) -> np.ndarray:
        if self.exons.shape[0] <= 1:
            return np.empty((0, 2), dtype=np.int32)
        ends, starts = self.exons[:-1, 1], self.exons[1:, 0]
        return np.stack([ends, starts], axis=1).astype(np.int32)


class TranscriptIndex:
    """Fast, read-only index built from a GTF/GFF. O(1) lookups for blocks & metadata."""

    def __init__(self, tx_by_id: Dict[str, TxRecord], gene_to_tx: Dict[str, List[str]],
                 genename_to_tx: Dict[str, List[str]], cache_key: str):
        self._tx_by_id = tx_by_id
        self._gene_to_tx = gene_to_tx
        self._genename_to_tx = genename_to_tx
        self._cache_key = cache_key

        # Versionless alias map (match ENST… to ENST….7)
        self._tx_by_id_novers: Dict[str, TxRecord] = {}
        for tid, rec in tx_by_id.items():
            base = re.sub(r"\.\d+$", "", tid)
            self._tx_by_id_novers.setdefault(base, rec)

    # ---------------------------------------------------------------------
    @classmethod
    def build(cls, gtf_path: str, cache_dir: Optional[str] = None, *,
              keep_features: Tuple[str, ...] = ("exon", "CDS", "5UTR", "3UTR"),
              protein_coding_only: bool = False,
              keep_chroms: Optional[Tuple[str, ...]] = None) -> "TranscriptIndex":

        gtf_path = str(pathlib.Path(gtf_path).resolve())

        salt = f".pc{int(protein_coding_only)}.kf{hashlib.sha1(','.join(keep_features).encode()).hexdigest()[:6]}"
        if keep_chroms:
            salt += f".kc{hashlib.sha1(','.join(keep_chroms).encode()).hexdigest()[:6]}"

        key = cls._cache_key(gtf_path) + salt
        cache_file = (os.path.join(cache_dir, f"txindex.{key}.pkl") if cache_dir else None)

        if cache_file and os.path.exists(cache_file):
            with open(cache_file, "rb") as f:
                return pickle.load(f)

        # 1) Load & normalize schema
        df = pr.read_gtf(gtf_path).df

        # Column normalization
        desired = ["Feature","Chromosome","Start","End","Strand",
                   "gene_id","gene_name","transcript_id",
                   "transcript_name","transcript_type"]

        if "transcript_type" not in df.columns and "transcript_biotype" in df.columns:
            df["transcript_type"] = df["transcript_biotype"]

        for c in desired:
            if c not in df.columns:
                df[c] = pd.NA

        df = df[desired].copy()

        # Normalize UTR labels
        df["Feature"] = df["Feature"].replace({
            "five_prime_UTR": "5UTR",
            "three_prime_UTR": "3UTR"
        })

        # Optional filters
        if keep_chroms is not None:
            df = df[df["Chromosome"].isin(keep_chroms)]
        if protein_coding_only and "transcript_type" in df.columns:
            df = df[df["transcript_type"] == "protein_coding"]

        df = df[df["Feature"].isin(keep_features)]

        # Dtypes
        df["Start"] = pd.to_numeric(df["Start"], errors="coerce").astype("Int64").astype("float64").astype("int32", errors="ignore")
        df["End"] = pd.to_numeric(df["End"], errors="coerce").astype("Int64").astype("float64").astype("int32", errors="ignore")
        df["strand_int"] = df["Strand"].map({"+": 1, "-": -1}).astype("Int8").fillna(0).astype("int8")

        if df.empty or df["transcript_id"].isna().all():
            raise RuntimeError(f"No transcript rows retained for {gtf_path}. Check file, species, or filters.")
        # 2) Global stable sort
        df.sort_values(["transcript_id", "Start", "End"],
                       kind="mergesort", inplace=True, ignore_index=True)

        # 3) Factorize per-transcript slices
        tid_codes, tid_uniques = pd.factorize(df["transcript_id"].astype(str), sort=False)
        change = np.r_[True, tid_codes[1:] != tid_codes[:-1], True]
        bounds = np.flatnonzero(change)
        starts, ends = bounds[:-1], bounds[1:]

        # Column numpy views
        feat = df["Feature"].to_numpy()
        chrom = df["Chromosome"].astype(str).to_numpy()
        start = df["Start"].to_numpy()
        end = df["End"].to_numpy()
        strand_int = df["strand_int"].to_numpy()
        gene_id = df["gene_id"].astype(str).to_numpy()
        gene_name = df["gene_name"].astype(str).to_numpy()
        tx_name = df["transcript_name"].astype(str).to_numpy()
        tx_type = df["transcript_type"].astype(str).to_numpy()

        # Feature masks
        f_exon = (feat == "exon")
        f_cds = (feat == "CDS")
        f_u5 = (feat == "5UTR")
        f_u3 = (feat == "3UTR")

        def _blocks_slice(i0: int, i1: int, mask: np.ndarray) -> np.ndarray:
            if i1 <= i0:
                return np.empty((0, 2), np.int32)
            loc = np.nonzero(mask[i0:i1])[0]
            if loc.size == 0:
                return np.empty((0, 2), np.int32)
            s = start[i0 + loc]
            e = end[i0 + loc]
            out = np.empty((loc.size, 2), dtype=np.int32)
            out[:, 0] = s
            out[:, 1] = e
            return out

        def _first_non_empty(a: np.ndarray) -> Optional[str]:
            for v in a:
                if v and v != "nan":
                    return str(v)
            return None

        tx_by_id: Dict[str, TxRecord] = {}
        gene_to_tx: Dict[str, List[str]] = {}
        genename_to_tx: Dict[str, List[str]] = {}

        for code, i0, i1 in zip(range(len(starts)), starts, ends):
            tid = str(tid_uniques[code])
            chrom0 = chrom[i0]
            sgn = int(strand_int[i0]) if strand_int[i0] in (1, -1) else 0
            gid = _first_non_empty(gene_id[i0:i1])
            gnm = _first_non_empty(gene_name[i0:i1])
            tnm = _first_non_empty(tx_name[i0:i1])
            ttp = _first_non_empty(tx_type[i0:i1])

            # guard against NaN starts/ends
            s_min = start[i0:i1][~np.isnan(start[i0:i1])]
            e_max = end[i0:i1][~np.isnan(end[i0:i1])]
            if s_min.size == 0 or e_max.size == 0:
                continue

            rec = TxRecord(
                transcript_id=tid,
                gene_id=gid,
                gene_name=gnm,
                transcript_name=tnm,
                transcript_type=ttp,
                chrom=chrom0,
                strand=sgn,
                span=(int(np.min(s_min)), int(np.max(e_max))),
                exons=_blocks_slice(i0, i1, f_exon),
                cds=_blocks_slice(i0, i1, f_cds),
                utr5=_blocks_slice(i0, i1, f_u5),
                utr3=_blocks_slice(i0, i1, f_u3),
            )

            tx_by_id[tid] = rec
            if gid:
                gene_to_tx.setdefault(gid, []).append(tid)
            if gnm:
                genename_to_tx.setdefault(gnm, []).append(tid)

        idx = cls(tx_by_id, gene_to_tx, genename_to_tx, key)

        # refuse to cache an empty index
        if cache_dir:
            if len(tx_by_id) == 0:
                raise RuntimeError("TranscriptIndex built empty — refusing to cache. Check GTF and filters.")
            os.makedirs(cache_dir, exist_ok=True)
            with open(cache_file, "wb") as f:
                pickle.dump(idx, f, protocol=pickle.HIGHEST_PROTOCOL)

        return idx

    # --------- version-tolerant lookups ---------
    def _resolve(self, tid: str) -> TxRecord:
        if tid in self._tx_by_id:
            return self._tx_by_id[tid]
        base = re.sub(r"\.\d+$", "", tid)
        rec = self._tx_by_id_novers.get(base)
        if rec is None:
            raise KeyError(tid)
        return rec

    def tx(self, tid: str) -> TxRecord:
        return self._resolve(tid)

    def exons(self, tid: str) -> np.ndarray:
        return self._resolve(tid).exons

    def cds(self, tid: str) -> np.ndarray:
        return self._resolve(tid).cds

    def utr5(self, tid: str) -> np.ndarray:
        return self._resolve(tid).utr5

    def utr3(self, tid: str) -> np.ndarray:
        return self._resolve(tid).utr3

    def junctions(self, tid: str) -> np.ndarray:
        return self._resolve(tid).junctions

    def chrom(self, tid: str) -> str:
        return self._resolve(tid).chrom

    def strand(self, tid: str) -> int:
        return self._resolve(tid).strand

    def span(self, tid: str) -> Tuple[int, int]:
        return self._resolve(tid).span

    def transcripts_of_gene(self, key: str) -> List[str]:
        return self._gene_to_tx.get(key, self._genename_to_tx.get(key, []))


    # --------- gene name mapping ---------
    def add_gene_names(self, gene_name_map: Union[str, Dict[str, str], pd.DataFrame],
                        transcript_id_col: Optional[str] = None,
                        gene_name_col: Optional[str] = None) -> int:
        """Add or update gene_name for transcripts using a mapping.

        Useful for GFF files (like PacBio) that lack gene_name attributes.
        Updates records in-place and rebuilds the genename_to_tx index.

        Parameters
        ----------
        gene_name_map : str, dict, or DataFrame
            Mapping from transcript_id to gene_name. Can be:
            - Path to TSV file with columns [transcript_id, gene_name]
            - Dict mapping transcript_id -> gene_name
            - DataFrame (use transcript_id_col and gene_name_col to specify columns)
            For PacBio format where transcript_id contains gene name suffix
            (e.g., 'PB.10.82:DDX11L17'), the base transcript_id (before ':')
            will be extracted for matching.
        transcript_id_col : str, optional
            Column name for transcript_id in DataFrame. If None, uses first column.
        gene_name_col : str, optional
            Column name for gene_name in DataFrame. If None, uses second column.

        Returns
        -------
        int
            Number of transcripts updated.
        """
        # Parse the mapping into a dict
        if isinstance(gene_name_map, str):
            # Load from TSV file
            map_df = pd.read_csv(gene_name_map, sep="\t", header=None, names=["tid_raw", "gene_name"])
            mapping = {}
            for _, row in map_df.iterrows():
                tid_raw = str(row["tid_raw"])
                gnm = str(row["gene_name"])
                # Handle PacBio format: PB.10.82:DDX11L17 -> PB.10.82
                if ":" in tid_raw:
                    tid = tid_raw.split(":")[0]
                else:
                    tid = tid_raw
                mapping[tid] = gnm
        elif isinstance(gene_name_map, pd.DataFrame):
            mapping = {}
            # Use specified columns, or fall back to positional
            if transcript_id_col and gene_name_col:
                tid_col, gnm_col = transcript_id_col, gene_name_col
            elif "transcript_id" in gene_name_map.columns and "gene_name" in gene_name_map.columns:
                tid_col, gnm_col = "transcript_id", "gene_name"
            else:
                tid_col, gnm_col = gene_name_map.columns[0], gene_name_map.columns[1]
            for _, row in gene_name_map.iterrows():
                tid_raw = str(row[tid_col])
                gnm = str(row[gnm_col])
                if ":" in tid_raw:
                    tid = tid_raw.split(":")[0]
                else:
                    tid = tid_raw
                mapping[tid] = gnm
        else:
            # Assume it's a dict
            mapping = {}
            for tid_raw, gnm in gene_name_map.items():
                if ":" in tid_raw:
                    tid = tid_raw.split(":")[0]
                else:
                    tid = tid_raw
                mapping[tid] = gnm

        # Update records
        updated = 0
        new_tx_by_id = {}
        new_genename_to_tx: Dict[str, List[str]] = {}

        for tid, rec in self._tx_by_id.items():
            gnm = mapping.get(tid)
            # Check if we should update: gnm is valid AND rec.gene_name is missing/NA
            gnm_valid = gnm and gnm not in ("nan", "<NA>", "None", "")
            rec_missing = rec.gene_name is None or pd.isna(rec.gene_name) or str(rec.gene_name) in ("nan", "<NA>", "None", "")
            if gnm_valid and rec_missing:
                # Create new record with updated gene_name
                new_rec = TxRecord(
                    transcript_id=rec.transcript_id,
                    gene_id=rec.gene_id,
                    gene_name=gnm,
                    transcript_name=rec.transcript_name,
                    transcript_type=rec.transcript_type,
                    chrom=rec.chrom,
                    strand=rec.strand,
                    span=rec.span,
                    exons=rec.exons,
                    cds=rec.cds,
                    utr5=rec.utr5,
                    utr3=rec.utr3,
                )
                new_tx_by_id[tid] = new_rec
                updated += 1
            else:
                new_tx_by_id[tid] = rec
                gnm = rec.gene_name

            # Rebuild genename_to_tx
            if gnm and gnm != "nan":
                new_genename_to_tx.setdefault(gnm, []).append(tid)

        self._tx_by_id = new_tx_by_id
        self._genename_to_tx = new_genename_to_tx

        # Rebuild versionless lookup
        self._tx_by_id_novers = {}
        for tid, rec in self._tx_by_id.items():
            base = re.sub(r"\\.\d+$", "", tid)
            self._tx_by_id_novers.setdefault(base, rec)

        return updated

    # --------- pigeon classification ---------
    def add_pigeon_classification(self, classification_file: str, use_ref_ids: bool = True) -> int:
        """Add metadata from PacBio pigeon classification file.
        
        Adds CDS coordinates, associated_transcript, subcategory, and NMD prediction
        from the pigeon classification.txt file.
        
        Parameters
        ----------
        classification_file : str
            Path to pigeon_filtered.classification.txt file.
        use_ref_ids : bool
            If True, remap transcript IDs to use reference IDs (e.g., ENST...) 
            when available, keeping PB.* IDs only for novel transcripts.
            This helps match adata that uses mixed ID formats. Default True.
            
        Returns
        -------
        int
            Number of transcripts updated with CDS information.
        """
        import pandas as pd
        
        # Load classification file
        clf = pd.read_csv(classification_file, sep="\t", low_memory=False)
        
        # Create metadata dict if not exists
        if not hasattr(self, '_metadata'):
            self._metadata: Dict[str, Dict] = {}
        
        # Create ID mapping dict: pb_id -> new_id
        if not hasattr(self, '_id_map'):
            self._id_map: Dict[str, str] = {}
        
        updated_cds = 0
        new_tx_by_id = {}
        new_genename_to_tx: Dict[str, List[str]] = {}
        
        for _, row in clf.iterrows():
            pb_id = str(row['isoform'])
            assoc_tx = row.get('associated_transcript')
            
            # Determine the ID to use
            if use_ref_ids and pd.notna(assoc_tx) and assoc_tx != 'novel' and not str(assoc_tx).startswith('PB.'):
                new_id = str(assoc_tx)
            else:
                new_id = pb_id
            
            # Store ID mapping
            self._id_map[pb_id] = new_id
            self._id_map[new_id] = new_id  # Also map new_id to itself for lookups
            
            # Store metadata under both IDs
            meta = {
                'pb_id': pb_id,
                'associated_gene': row.get('associated_gene'),
                'associated_transcript': assoc_tx,
                'structural_category': row.get('structural_category'),
                'subcategory': row.get('subcategory'),
                'coding': row.get('coding'),
                'predicted_NMD': row.get('predicted_NMD'),
            }
            self._metadata[pb_id] = meta
            self._metadata[new_id] = meta
            
            # Update transcript record
            if pb_id in self._tx_by_id:
                rec = self._tx_by_id[pb_id]
                gene_name = row.get('associated_gene')
                
                # Compute CDS blocks from genomic coordinates
                cds_start = row.get('CDS_genomic_start')
                cds_end = row.get('CDS_genomic_end')
                
                new_cds = rec.cds
                if pd.notna(cds_start) and pd.notna(cds_end) and rec.exons.size > 0:
                    cds_start, cds_end = int(cds_start), int(cds_end)
                    if cds_start > 0 and cds_end > 0:
                        # Compute CDS blocks by intersecting with exons
                        cds_blocks = []
                        for ex_start, ex_end in rec.exons:
                            block_start = max(ex_start, cds_start)
                            block_end = min(ex_end, cds_end)
                            if block_start < block_end:
                                cds_blocks.append([block_start, block_end])
                        
                        if cds_blocks:
                            new_cds = np.array(cds_blocks, dtype=np.int32)
                            updated_cds += 1
                
                # Update gene_name if needed
                rec_missing_gene = rec.gene_name is None or pd.isna(rec.gene_name) or str(rec.gene_name) in ("nan", "<NA>", "None", "")
                new_gene_name = str(gene_name) if (gene_name and pd.notna(gene_name) and rec_missing_gene) else rec.gene_name
                
                # Create updated record with new ID
                new_rec = TxRecord(
                    transcript_id=new_id,
                    gene_id=rec.gene_id,
                    gene_name=new_gene_name,
                    transcript_name=rec.transcript_name,
                    transcript_type=rec.transcript_type,
                    chrom=rec.chrom,
                    strand=rec.strand,
                    span=rec.span,
                    exons=rec.exons,
                    cds=new_cds,
                    utr5=rec.utr5,
                    utr3=rec.utr3,
                )
                new_tx_by_id[new_id] = new_rec
                
                # Update gene mappings
                if new_gene_name and str(new_gene_name) not in ("nan", "<NA>", "None", ""):
                    new_genename_to_tx.setdefault(new_gene_name, []).append(new_id)
        
        # Replace tx_by_id with remapped version
        # Keep transcripts not in classification file
        for tid, rec in self._tx_by_id.items():
            if tid not in [row['isoform'] for _, row in clf.iterrows()]:
                new_tx_by_id[tid] = rec
        
        self._tx_by_id = new_tx_by_id
        self._genename_to_tx = new_genename_to_tx
        
        # Rebuild gene_to_tx
        self._gene_to_tx = {}
        for tid, rec in self._tx_by_id.items():
            if rec.gene_id:
                self._gene_to_tx.setdefault(rec.gene_id, []).append(tid)
        
        # Rebuild versionless lookup
        self._tx_by_id_novers = {}
        for tid, rec in self._tx_by_id.items():
            base = re.sub(r"\.\d+$", "", tid)
            self._tx_by_id_novers.setdefault(base, rec)
        
        return updated_cds
    
    def get_metadata(self, tid: str) -> Optional[Dict]:
        """Get pigeon classification metadata for a transcript."""
        if not hasattr(self, '_metadata'):
            return None
        return self._metadata.get(tid)
    
    def to_gtf(self, output_path: str, include_cds: bool = True) -> None:
        """Export the transcript index to GTF format.
        
        Writes a standard GTF file with proper 1-based coordinates and CDS frame.
        
        Parameters
        ----------
        output_path : str
            Path to write the GTF file.
        include_cds : bool
            If True, include CDS features with proper frame (default True).
        """
        with open(output_path, 'w') as f:
            for tid, rec in self._tx_by_id.items():
                chrom = rec.chrom
                strand = '+' if rec.strand >= 0 else '-'
                gene_id = rec.gene_id or tid.rsplit('.', 1)[0]
                gene_name = rec.gene_name or gene_id
                
                # Get metadata if available
                meta = self.get_metadata(tid) if hasattr(self, '_metadata') else None
                
                # Build attribute string
                attrs = f'gene_id "{gene_id}"; transcript_id "{tid}"; gene_name "{gene_name}";'
                if meta:
                    if meta.get('pb_id') and meta.get('pb_id') != tid:
                        attrs += f' pb_id "{meta["pb_id"]}";'
                    if meta.get('associated_transcript'):
                        attrs += f' associated_transcript "{meta["associated_transcript"]}";'
                    if meta.get('structural_category'):
                        attrs += f' structural_category "{meta["structural_category"]}";'
                    if meta.get('subcategory'):
                        attrs += f' subcategory "{meta["subcategory"]}";'
                    if meta.get('coding'):
                        attrs += f' transcript_biotype "{meta["coding"]}";'
                    if meta.get('predicted_NMD'):
                        attrs += f' predicted_NMD "{meta["predicted_NMD"]}";'
                
                # GTF uses 1-based coordinates
                tx_start, tx_end = rec.span
                tx_start_1 = tx_start + 1  # Convert to 1-based
                
                # Write transcript/gene line
                f.write(f"{chrom}\tTranscriptData\ttranscript\t{tx_start_1}\t{tx_end}\t.\t{strand}\t.\t{attrs}\n")
                
                # Write exon lines (sorted by position)
                exons_sorted = sorted(rec.exons.tolist(), key=lambda x: x[0])
                for i, (ex_start, ex_end) in enumerate(exons_sorted):
                    exon_num = i + 1 if strand == '+' else len(exons_sorted) - i
                    exon_attrs = attrs + f' exon_number "{exon_num}";'
                    ex_start_1 = ex_start + 1  # Convert to 1-based
                    f.write(f"{chrom}\tTranscriptData\texon\t{ex_start_1}\t{ex_end}\t.\t{strand}\t.\t{exon_attrs}\n")
                
                # Write CDS lines with proper frame
                if include_cds and rec.cds.size > 0:
                    cds_sorted = sorted(rec.cds.tolist(), key=lambda x: x[0])
                    
                    # Calculate frame for each CDS block
                    # Frame = (3 - (cumulative CDS length % 3)) % 3
                    if strand == '+':
                        cumulative_len = 0
                        for cds_start, cds_end in cds_sorted:
                            frame = (3 - (cumulative_len % 3)) % 3
                            cds_start_1 = cds_start + 1  # Convert to 1-based
                            cds_attrs = attrs
                            f.write(f"{chrom}\tTranscriptData\tCDS\t{cds_start_1}\t{cds_end}\t.\t{strand}\t{frame}\t{cds_attrs}\n")
                            cumulative_len += (cds_end - cds_start)
                    else:
                        # For minus strand, process in reverse
                        cumulative_len = 0
                        for cds_start, cds_end in reversed(cds_sorted):
                            frame = (3 - (cumulative_len % 3)) % 3
                            cds_start_1 = cds_start + 1  # Convert to 1-based
                            cds_attrs = attrs
                            f.write(f"{chrom}\tTranscriptData\tCDS\t{cds_start_1}\t{cds_end}\t.\t{strand}\t{frame}\t{cds_attrs}\n")
                            cumulative_len += (cds_end - cds_start)
                
                # Write start_codon and stop_codon if CDS present
                if include_cds and rec.cds.size > 0:
                    cds_sorted = sorted(rec.cds.tolist(), key=lambda x: x[0])
                    if strand == '+':
                        # Start codon at beginning of first CDS
                        start_pos = cds_sorted[0][0] + 1  # 1-based
                        stop_pos = cds_sorted[-1][1] - 2  # Last 3 bp, 1-based
                        f.write(f"{chrom}\tTranscriptData\tstart_codon\t{start_pos}\t{start_pos + 2}\t.\t{strand}\t0\t{attrs}\n")
                        f.write(f"{chrom}\tTranscriptData\tstop_codon\t{stop_pos}\t{stop_pos + 2}\t.\t{strand}\t0\t{attrs}\n")
                    else:
                        # Minus strand: start at end, stop at beginning
                        start_pos = cds_sorted[-1][1] - 2  # 1-based
                        stop_pos = cds_sorted[0][0] + 1  # 1-based
                        f.write(f"{chrom}\tTranscriptData\tstart_codon\t{start_pos}\t{start_pos + 2}\t.\t{strand}\t0\t{attrs}\n")
                        f.write(f"{chrom}\tTranscriptData\tstop_codon\t{stop_pos}\t{stop_pos + 2}\t.\t{strand}\t0\t{attrs}\n")

    # --------- small debuggers ---------
    def summary(self) -> Dict[str, object]:
        return {
            "n_transcripts": len(self._tx_by_id),
            "n_genes_by_id": len(self._gene_to_tx),
            "n_genes_by_name": len(self._genename_to_tx),
            "cache_key": self._cache_key,
        }

    def list_transcripts(self, n: int = 10, prefix: Optional[str] = None) -> List[str]:
        ids = list(self._tx_by_id.keys())
        if prefix:
            ids = [t for t in ids if t.startswith(prefix)]
        return ids[:n]

    # --------- preprocessing helpers ---------
    def gene_transcript_table(self, use_gene_name: bool = True) -> pd.DataFrame:
        """Return DataFrame with columns [gene, transcript_id] for preprocessing functions.
        
        Parameters
        ----------
        use_gene_name : bool
            If True, use gene_name (symbol) as gene identifier; otherwise use gene_id (ENSG).
        
        Returns
        -------
        pd.DataFrame
            DataFrame with columns ['gene', 'transcript_id'], version-stripped.
        """
        rows = []
        for tid, rec in self._tx_by_id.items():
            gene = (rec.gene_name if use_gene_name and rec.gene_name else rec.gene_id) or ""
            tid_stripped = tid.split(".")[0]
            rows.append((gene, tid_stripped))
        return pd.DataFrame(rows, columns=["gene", "transcript_id"]).drop_duplicates()

    def isoforms_per_gene(self, use_gene_name: bool = True) -> pd.Series:
        """Return Series of isoform counts per gene (fast, no groupby needed).
        
        Parameters
        ----------
        use_gene_name : bool
            If True, use gene_name mapping; otherwise use gene_id mapping.
        
        Returns
        -------
        pd.Series
            Series indexed by gene with isoform counts as values.
        """
        mapping = self._genename_to_tx if use_gene_name else self._gene_to_tx
        return pd.Series({gene: len(tids) for gene, tids in mapping.items()}, name="n_isoforms")

    def transcript_length(self, tid: str) -> int:
        """Return mature transcript length (sum of exon lengths) in bp."""
        exons = self._resolve(tid).exons
        if exons.size == 0:
            return 0
        return int(np.sum(exons[:, 1] - exons[:, 0]))

    def transcript_lengths_table(self) -> pd.DataFrame:
        """Return DataFrame with transcript_id and length for all transcripts."""
        rows = []
        for tid, rec in self._tx_by_id.items():
            length = int(np.sum(rec.exons[:, 1] - rec.exons[:, 0])) if rec.exons.size > 0 else 0
            tid_stripped = tid.split(".")[0]
            gene = rec.gene_name or rec.gene_id or ""
            rows.append((tid_stripped, tid, gene, length))
        return pd.DataFrame(rows, columns=["transcript_id", "transcript_id_full", "gene", "length"])

    @staticmethod
    def _cache_key(gtf_path: str) -> str:
        st = pathlib.Path(gtf_path).stat()
        return hashlib.sha1(f"{gtf_path}|{st.st_size}|{int(st.st_mtime)}".encode()).hexdigest()[:16]
    
    def _tx_exon_lists_for_bubbles(rec: TxRecord) -> tuple[list[int], list[int]]:
        """
        Reconstruct exonStart / exonEnd lists in the same way ParseGTF does.

        For '+' strand:
        exonStart = sort(Start), exonEnd = sort(End)

        For '-' strand:
        exonStart = -sort(-End)
        exonEnd   = -sort(-Start)

        This preserves Wang's 5'/3' conventions and bubble classification semantics.
        """
        from numpy import sort as npsort

        ex = rec.exons
        if ex.size == 0:
            return [], []

        starts = ex[:, 0].astype(int)
        ends   = ex[:, 1].astype(int)

        if rec.strand == 1:   # '+'
            exonStart = npsort(starts)
            exonEnd   = npsort(ends)
        elif rec.strand == -1:  # '-'
            exonStart = -npsort(-ends)
            exonEnd   = -npsort(-starts)
        else:
            # If you ever have strand==0, you can either raise or treat as '+'.
            raise ValueError(f"Unsupported strand {rec.strand} for {rec.transcript_id}")

        return exonStart.astype(int).tolist(), exonEnd.astype(int).tolist()




# %% ../nbs/002_transcript_data.ipynb #e547b119
def _build_pair_df_from_index(idx: TranscriptIndex,
                                tid1: str,
                                tid2: str) -> pd.DataFrame:
        """
        Create the 2-row inputDF equivalent to Wang's ParseGTF+SmoothEnds output.
        """
        rec1 = idx.tx(tid1)
        rec2 = idx.tx(tid2)

        if rec1.chrom != rec2.chrom:
            raise ValueError(f"Transcripts are on different chromosomes: "
                            f"{rec1.chrom} vs {rec2.chrom}")
        if rec1.strand != rec2.strand:
            raise ValueError(f"Transcripts are on different strands: "
                            f"{rec1.strand} vs {rec2.strand}")

        exonStart1, exonEnd1 = _tx_exon_lists_for_bubbles(rec1)
        exonStart2, exonEnd2 = _tx_exon_lists_for_bubbles(rec2)

        strand_char = "+" if rec1.strand == 1 else "-"

        inputDF = pd.DataFrame(
            [
                [rec1.transcript_id, rec1.chrom, strand_char, exonStart1, exonEnd1],
                [rec2.transcript_id, rec2.chrom, strand_char, exonStart2, exonEnd2],
            ],
            columns=["transcript_ID", "chrom", "strand", "exonStart", "exonEnd"],
        )

        # Apply Wang's "smoothing" of overlapping terminal exons
        inputDF = SmoothEnds(inputDF)
        return inputDF
    
    
def classify_transcript_pair_from_index(idx: TranscriptIndex,
                                        tid1: str,
                                        tid2: str) -> pd.DataFrame:
    """
    Enumerate transcript-structure differences between two isoforms using Wang's
    bubble algorithm, backed by our TranscriptIndex.

    Returns a DataFrame with columns:
        ['transcript1', 'transcript2', 'event', 'coordinates']
    """
    inputDF = _build_pair_df_from_index(idx, tid1, tid2)

    chrom = str(inputDF["chrom"].iloc[0])
    strand_char = inputDF["strand"].iloc[0]

    spliceGraph = BuildSpliceGraph(inputDF)
    attributes = get_node_attributes(spliceGraph, "attribute")
    bubbles = FindBubbles(spliceGraph)

    out_rows = []
    t1 = inputDF["transcript_ID"].iloc[0]
    t2 = inputDF["transcript_ID"].iloc[1]

    for bubble in bubbles:
        event, coord = ClassifyBubble(bubble, attributes)

        if coord != "NA":
            # coord is something like "start:end;start:end" (no chrom/strand yet)
            coord = ";".join(
                [f"{chrom}:{x}:{strand_char}" for x in coord.split(";")]
            )

        out_rows.append((t1, t2, event, coord))

    return pd.DataFrame(out_rows,
                        columns=["transcript1", "transcript2", "event", "coordinates"])



# %% ../nbs/002_transcript_data.ipynb #71ca6e15
def _tx_exon_lists_for_bubbles(rec: TxRecord) -> tuple[list[int], list[int]]:
    """
    Reconstruct exonStart / exonEnd lists in the same way ParseGTF does.

    For '+' strand:
      exonStart = sort(Start), exonEnd = sort(End)

    For '-' strand:
      exonStart = -sort(-End)
      exonEnd   = -sort(-Start)

    This preserves Wang's 5'/3' conventions and bubble classification semantics.
    """
    from numpy import sort as npsort

    ex = rec.exons
    if ex.size == 0:
        return [], []

    starts = ex[:, 0].astype(int)
    ends   = ex[:, 1].astype(int)

    if rec.strand == 1:   # '+'
        exonStart = npsort(starts)
        exonEnd   = npsort(ends)
    elif rec.strand == -1:  # '-'
        exonStart = -npsort(-ends)
        exonEnd   = -npsort(-starts)
    else:
        # If you ever have strand==0, you can either raise or treat as '+'.
        raise ValueError(f"Unsupported strand {rec.strand} for {rec.transcript_id}")

    return exonStart.astype(int).tolist(), exonEnd.astype(int).tolist()


def _build_pair_df_from_index(idx: TranscriptIndex,
                              tid1: str,
                              tid2: str) -> pd.DataFrame:
    """
    Create the 2-row inputDF equivalent to Wang's ParseGTF+SmoothEnds output.
    """
    rec1 = idx.tx(tid1)
    rec2 = idx.tx(tid2)

    if rec1.chrom != rec2.chrom:
        raise ValueError(f"Transcripts are on different chromosomes: "
                         f"{rec1.chrom} vs {rec2.chrom}")
    if rec1.strand != rec2.strand:
        raise ValueError(f"Transcripts are on different strands: "
                         f"{rec1.strand} vs {rec2.strand}")

    exonStart1, exonEnd1 = _tx_exon_lists_for_bubbles(rec1)
    exonStart2, exonEnd2 = _tx_exon_lists_for_bubbles(rec2)

    strand_char = "+" if rec1.strand == 1 else "-"

    inputDF = pd.DataFrame(
        [
            [rec1.transcript_id, rec1.chrom, strand_char, exonStart1, exonEnd1],
            [rec2.transcript_id, rec2.chrom, strand_char, exonStart2, exonEnd2],
        ],
        columns=["transcript_ID", "chrom", "strand", "exonStart", "exonEnd"],
    )

    # Apply Wang's "smoothing" of overlapping terminal exons
    inputDF = SmoothEnds(inputDF)
    return inputDF


# %% ../nbs/002_transcript_data.ipynb #8fe1ec98
from typing import List, Optional, Tuple
import numpy as np
import pandas as pd
import pyranges as pr

def _reverse_complement(seq: str) -> str:
    """Reverse complement a DNA sequence."""
    complement = {
        'A': 'T', 'C': 'G', 'G': 'C', 'T': 'A',
        'a': 't', 'c': 'g', 'g': 'c', 't': 'a',
        'N': 'N', 'n': 'n'
    }
    return ''.join(complement.get(base, base) for base in reversed(seq))


# Standard genetic code
CODON_TABLE = {
    'TTT': 'F', 'TTC': 'F', 'TTA': 'L', 'TTG': 'L',
    'TCT': 'S', 'TCC': 'S', 'TCA': 'S', 'TCG': 'S',
    'TAT': 'Y', 'TAC': 'Y', 'TAA': '*', 'TAG': '*',
    'TGT': 'C', 'TGC': 'C', 'TGA': '*', 'TGG': 'W',
    'CTT': 'L', 'CTC': 'L', 'CTA': 'L', 'CTG': 'L',
    'CCT': 'P', 'CCC': 'P', 'CCA': 'P', 'CCG': 'P',
    'CAT': 'H', 'CAC': 'H', 'CAA': 'Q', 'CAG': 'Q',
    'CGT': 'R', 'CGC': 'R', 'CGA': 'R', 'CGG': 'R',
    'ATT': 'I', 'ATC': 'I', 'ATA': 'I', 'ATG': 'M',
    'ACT': 'T', 'ACC': 'T', 'ACA': 'T', 'ACG': 'T',
    'AAT': 'N', 'AAC': 'N', 'AAA': 'K', 'AAG': 'K',
    'AGT': 'S', 'AGC': 'S', 'AGA': 'R', 'AGG': 'R',
    'GTT': 'V', 'GTC': 'V', 'GTA': 'V', 'GTG': 'V',
    'GCT': 'A', 'GCC': 'A', 'GCA': 'A', 'GCG': 'A',
    'GAT': 'D', 'GAC': 'D', 'GAA': 'E', 'GAG': 'E',
    'GGT': 'G', 'GGC': 'G', 'GGA': 'G', 'GGG': 'G',
}

def _translate_cds(cds_seq: str) -> str:
    """Translate CDS sequence to protein, stopping at first stop codon."""
    if not cds_seq or len(cds_seq) < 3:
        return ""

    protein = []
    for i in range(0, len(cds_seq) - 2, 3):
        codon = cds_seq[i:i+3]
        aa = CODON_TABLE.get(codon, 'X')
        if aa == '*':  # Stop codon
            break
        protein.append(aa)

    return ''.join(protein)


class TranscriptData:
    """Fast, drop-in replacement for your old TranscriptData, backed by TranscriptIndex."""

    def __init__(self, gtf_file: str, reference_fasta: Optional[str] = None, cache_dir: Optional[str] = None,
                 gene_name_map: Optional[Union[str, Dict[str, str], pd.DataFrame]] = None,
                 transcript_id_col: Optional[str] = None, gene_name_col: Optional[str] = None):
        """Initialize TranscriptData from a GTF/GFF file.
        
        Parameters
        ----------
        gtf_file : str
            Path to GTF/GFF file.
        reference_fasta : str, optional
            Path to reference genome FASTA for sequence retrieval.
        cache_dir : str, optional
            Directory to cache the built index.
        gene_name_map : str, dict, or DataFrame, optional
            Mapping from transcript_id to gene_name. Useful for GFF files
            (like PacBio) that lack gene_name attributes. Can be:
            - Path to TSV file with columns [transcript_id, gene_name]
            - Dict mapping transcript_id -> gene_name  
            - DataFrame (use transcript_id_col and gene_name_col to specify columns)
            For PacBio format (e.g., 'PB.10.82:DDX11L17'), the base
            transcript_id will be extracted for matching.
        transcript_id_col : str, optional
            Column name for transcript_id when gene_name_map is a DataFrame.
        gene_name_col : str, optional
            Column name for gene_name when gene_name_map is a DataFrame.
        """
        self.gtf_file = gtf_file
        self.reference_fasta = reference_fasta
        self._idx = TranscriptIndex.build(gtf_file, cache_dir=cache_dir)
        self._fasta_handle = None
        
        # Add gene names if mapping provided
        if gene_name_map is not None:
            self._idx.add_gene_names(gene_name_map, transcript_id_col=transcript_id_col, gene_name_col=gene_name_col)

    def _get_fasta_handle(self):
        """
        Get a pysam FastaFile handle, handling both compressed and uncompressed files.
        Uses pysam instead of pyfaidx to support 64-bit genomic coordinates.
        """
        if self._fasta_handle is not None:
            return self._fasta_handle

        if not self.reference_fasta:
            return None

        import pysam
        import gzip
        import shutil
        from pathlib import Path

        fasta_path = Path(self.reference_fasta)

        # Check if file is gzipped (pysam can handle bgzipped but not regular gzip)
        if fasta_path.suffix == '.gz':
            decompressed_path = fasta_path.with_suffix('')

            if (
                not decompressed_path.exists() or
                decompressed_path.stat().st_mtime < fasta_path.stat().st_mtime
            ):
                print(f"Decompressing {fasta_path.name} for pysam...")
                with gzip.open(fasta_path, 'rb') as f_in:
                    with open(decompressed_path, 'wb') as f_out:
                        shutil.copyfileobj(f_in, f_out)
                print(f"✓ Decompressed to {decompressed_path.name}")

            self._fasta_handle = pysam.FastaFile(str(decompressed_path))
        else:
            self._fasta_handle = pysam.FastaFile(str(fasta_path))

        return self._fasta_handle

    def _wrap(self, tid: str, arr: np.ndarray, feature: str) -> pr.PyRanges:
        if arr.size == 0:
            return pr.PyRanges(pd.DataFrame(columns=["Chromosome", "Start", "End", "Strand", "Feature"]))
        chrom = self._idx.chrom(tid)
        strand = "+" if self._idx.strand(tid) == 1 else "-"
        df = pd.DataFrame({
            "Chromosome": chrom,
            "Start": arr[:, 0],
            "End": arr[:, 1],
            "Strand": strand,
            "Feature": feature
        })
        return pr.PyRanges(df)

    def get_exons(self, tid: str) -> pr.PyRanges:
        return self._wrap(tid, self._idx.exons(tid), "exon")

    def get_cds(self, tid: str) -> pr.PyRanges:
        return self._wrap(tid, self._idx.cds(tid), "CDS")

    def get_utr(self, tid: str, utr_type: str = None) -> pr.PyRanges:
        if utr_type == "5UTR":
            return self._wrap(tid, self._idx.utr5(tid), "5UTR")
        if utr_type == "3UTR":
            return self._wrap(tid, self._idx.utr3(tid), "3UTR")

        a5, a3 = self._idx.utr5(tid), self._idx.utr3(tid)
        parts = []
        if a5.size:
            parts.append(self._wrap(tid, a5, "5UTR").df)
        if a3.size:
            parts.append(self._wrap(tid, a3, "3UTR").df)
        return pr.PyRanges(pd.concat(parts, ignore_index=True)) if parts else self._wrap(
            tid, np.empty((0, 2), np.int32), "UTR"
        )

    def get_intron_ranges(self, tid: str) -> pr.PyRanges:
        ex = self._idx.exons(tid)
        if ex.shape[0] <= 1:
            return pr.PyRanges(pd.DataFrame(columns=["Chromosome", "Start", "End", "Strand"]))

        intr = np.stack([ex[:-1, 1], ex[1:, 0]], axis=1)
        chrom = self._idx.chrom(tid)
        strand = "+" if self._idx.strand(tid) == 1 else "-"
        df = pd.DataFrame({
            "Chromosome": chrom,
            "Start": intr[:, 0],
            "End": intr[:, 1],
            "Strand": strand
        })
        return pr.PyRanges(df)

    def get_exon_coords_and_strand(self, tid: str) -> Tuple[List[List[int]], Optional[int]]:
        ex = self._idx.exons(tid)
        strand = self._idx.strand(tid)
        coords = [[int(e), int(s)] for s, e in ex]
        return coords, strand

    def get_transcript_length(self, tid: str) -> int:
        ex = self._idx.exons(tid)
        return int(np.maximum(0, ex[:, 1] - ex[:, 0]).sum()) if ex.size else 0

    def get_chromosome(self, tid: str) -> Optional[str]:
        return self._idx.chrom(tid)

    def get_strand(self, tid: str) -> Optional[int]:
        return self._idx.strand(tid)

    def get_transcripts_by_gene_id(self, gid: str) -> List[str]:
        return self._idx.transcripts_of_gene(gid)

    def get_transcripts_by_gene_name(self, gnm: str) -> List[str]:
        return self._idx.transcripts_of_gene(gnm)

    def arrays(self, tid: str) -> dict:
        return {
            "chrom": self._idx.chrom(tid),
            "strand": self._idx.strand(tid),
            "span": self._idx.span(tid),
            "exons": self._idx.exons(tid),
            "cds": self._idx.cds(tid),
            "utr5": self._idx.utr5(tid),
            "utr3": self._idx.utr3(tid),
            "junctions": self._idx.junctions(tid)
        }

    # --------- preprocessing helpers ---------
    def gene_transcript_table(self, use_gene_name: bool = True) -> pd.DataFrame:
        """Return DataFrame with columns [gene, transcript_id] for preprocessing functions.
        
        Parameters
        ----------
        use_gene_name : bool
            If True, use gene_name (symbol) as gene identifier; otherwise use gene_id (ENSG).
        
        Returns
        -------
        pd.DataFrame
            DataFrame with columns ['gene', 'transcript_id'], version-stripped.
        """
        return self._idx.gene_transcript_table(use_gene_name=use_gene_name)

    def isoforms_per_gene(self, use_gene_name: bool = True) -> pd.Series:
        """Return Series of isoform counts per gene.
        
        Parameters
        ----------
        use_gene_name : bool
            If True, use gene_name mapping; otherwise use gene_id mapping.
        
        Returns
        -------
        pd.Series
            Series indexed by gene with isoform counts as values.
        """
        return self._idx.isoforms_per_gene(use_gene_name=use_gene_name)

    def transcript_length(self, tid: str) -> int:
        """Return mature transcript length (sum of exon lengths) in bp."""
        return self._idx.transcript_length(tid)

    def transcript_lengths_table(self) -> pd.DataFrame:
        """Return DataFrame with transcript_id and length for all transcripts."""
        return self._idx.transcript_lengths_table()

    def get_exon_coords_and_strand_batch_fast(self, transcript_ids: tuple[str, ...]):
        out = {}
        idx = self._idx
        for tid in transcript_ids:
            ex = idx.exons(tid)
            st = idx.strand(tid)
            if ex.size:
                arr = np.empty_like(ex)
                arr[:, 0] = ex[:, 1]
                arr[:, 1] = ex[:, 0]
                ex_ls = arr.tolist()
            else:
                ex_ls = []
            out[tid] = (ex_ls, st)
        return out

    def get_cds_bounds_batch_fast(self, transcript_ids: tuple[str, ...]):
        out = {}
        idx = self._idx
        for tid in transcript_ids:
            cds = idx.cds(tid)
            if cds.size:
                out[tid] = (int(cds[:, 0].min()), int(cds[:, 1].max()))
            else:
                out[tid] = None
        return out

    def get_transcript_info(self, transcript_id: str) -> dict:
        tid = _versionless(transcript_id)
        rec = self._idx.tx(tid)
        cds = self._idx.cds(tid)
        return {
            "transcript_id": rec.transcript_id,
            "transcript_name": rec.transcript_name or "unknown",
            "transcript_type": rec.transcript_type or "unknown",
            "gene_id": rec.gene_id,
            "gene_name": rec.gene_name,
            "cds_start": int(cds[:, 0].min()) if cds.size else None,
            "cds_end": int(cds[:, 1].max()) if cds.size else None,
            "chromosome": rec.chrom,
            "strand": "+" if rec.strand == 1 else "-"
        }

    def get_transcript_sequence(self, transcript_id: str) -> Optional[str]:
        fa = self._get_fasta_handle()
        if fa is None:
            return None

        tid = _versionless(transcript_id)
        rec = self._idx.tx(tid)

        exons = rec.exons
        chrom = rec.chrom
        strand = rec.strand

        # Use pysam.fetch() which handles 64-bit coordinates properly
        seqs = []
        for start, end in exons:
            seq = fa.fetch(chrom, int(start), int(end))
            seqs.append(seq)

        transcript_seq = ''.join(seqs)

        if strand == -1:
            transcript_seq = _reverse_complement(transcript_seq)

        return transcript_seq.upper()

    def get_cds_sequence(self, transcript_id: str) -> Optional[str]:
        fa = self._get_fasta_handle()
        if fa is None:
            return None

        tid = _versionless(transcript_id)
        rec = self._idx.tx(tid)

        cds = rec.cds
        if cds.size == 0:
            return None

        chrom = rec.chrom
        strand = rec.strand

        # Use pysam.fetch() which handles 64-bit coordinates properly
        seqs = []
        for start, end in cds:
            seq = fa.fetch(chrom, int(start), int(end))
            seqs.append(seq)

        cds_seq = ''.join(seqs)

        if strand == -1:
            cds_seq = _reverse_complement(cds_seq)

        return cds_seq.upper()

    def get_protein_sequence(self, transcript_id: str) -> Optional[str]:
        cds_seq = self.get_cds_sequence(transcript_id)
        if not cds_seq:
            return None

        return _translate_cds(cds_seq)


    def add_gene_names(self, gene_name_map: Union[str, Dict[str, str], pd.DataFrame],
                        transcript_id_col: Optional[str] = None,
                        gene_name_col: Optional[str] = None) -> int:
        """Add or update gene_name for transcripts using a mapping.

        Useful for GFF files (like PacBio) that lack gene_name attributes.
        Delegates to TranscriptIndex.add_gene_names().

        Parameters
        ----------
        gene_name_map : str, dict, or DataFrame
            Mapping from transcript_id to gene_name. Can be:
            - Path to TSV file with columns [transcript_id, gene_name]
            - Dict mapping transcript_id -> gene_name
            - DataFrame (use transcript_id_col and gene_name_col to specify columns)
            For PacBio format (e.g., 'PB.10.82:DDX11L17'), the base
            transcript_id will be extracted for matching.
        transcript_id_col : str, optional
            Column name for transcript_id when gene_name_map is a DataFrame.
        gene_name_col : str, optional
            Column name for gene_name when gene_name_map is a DataFrame.

        Returns
        -------
        int
            Number of transcripts updated.
        
        Example
        -------
        >>> td = TranscriptData("pigeon_filtered.sorted.gff")
        >>> td.add_gene_names(adata.var, transcript_id_col="transcriptId", gene_name_col="geneId")
        14891
        """
        return self._idx.add_gene_names(gene_name_map, transcript_id_col=transcript_id_col, gene_name_col=gene_name_col)

    def add_pigeon_classification(self, classification_file: str, use_ref_ids: bool = True) -> int:
        """Add metadata from PacBio pigeon classification file.
        
        Adds CDS coordinates, associated_transcript, subcategory, and NMD prediction.
        Also updates gene_name from associated_gene column.
        
        Parameters
        ----------
        classification_file : str
            Path to pigeon_filtered.classification.txt file.
        use_ref_ids : bool
            If True, remap transcript IDs to use reference IDs (e.g., ENST...) 
            when available, keeping PB.* IDs only for novel transcripts.
            This helps match adata that uses mixed ID formats. Default True.
            
        Returns
        -------
        int
            Number of transcripts updated with CDS information.
            
        Example
        -------
        >>> td = TranscriptData("pigeon_filtered.sorted.gff")
        >>> td.add_pigeon_classification("pigeon_filtered.classification.txt")
        >>> # Now IDs match adata: ENST... for known, PB.* for novel
        >>> td.get_metadata("ENST00000456328.2")
        {'pb_id': 'PB.4.4', 'associated_gene': 'DDX11L1', ...}
        """
        return self._idx.add_pigeon_classification(classification_file, use_ref_ids=use_ref_ids)
    
    def get_metadata(self, tid: str) -> Optional[Dict]:
        """Get pigeon classification metadata for a transcript.
        
        Returns dict with keys: associated_gene, associated_transcript, 
        structural_category, subcategory, coding, predicted_NMD
        """
        return self._idx.get_metadata(tid)
    
    def to_gtf(self, output_path: str, include_cds: bool = True) -> None:
        """Export the transcript data to GTF format.
        
        Saves all transcript information including CDS and metadata annotations.
        The output GTF can be loaded directly with TranscriptData() next time.
        
        Parameters
        ----------
        output_path : str
            Path to write the GTF file.
        include_cds : bool
            If True, include CDS features (default True).
            
        Example
        -------
        >>> td = TranscriptData("pigeon_filtered.sorted.gff")
        >>> td.add_pigeon_classification("pigeon_filtered.classification.txt")
        >>> td.to_gtf("augmented_transcripts.gtf")
        >>> # Next time, just load the augmented GTF:
        >>> td = TranscriptData("augmented_transcripts.gtf")
        """
        self._idx.to_gtf(output_path, include_cds=include_cds)

    def get_gene_sequences(self, gene_name: str) -> Dict[str, str]:
        transcript_ids = self.get_transcripts_by_gene_name(gene_name)

        sequences = {}
        for tid in transcript_ids:
            seq = self.get_transcript_sequence(tid)
            if seq:
                sequences[tid] = seq

        return sequences

    def get_gene_proteins(self, gene_name: str) -> Dict[str, str]:
        transcript_ids = self.get_transcripts_by_gene_name(gene_name)

        proteins = {}
        for tid in transcript_ids:
            protein = self.get_protein_sequence(tid)
            if protein:
                proteins[tid] = protein

        return proteins

    def classify_splicing_events(self, tid1: str, tid2: str) -> pd.DataFrame:
        """
        High-level wrapper: compare two isoforms using the Wang bubble classifier.

        Example:
            td = TranscriptData(gtf_file, cache_dir=...)
            td.classify_splicing_events("ENST00000335137", "ENST000004XXXX")
        """
        return classify_transcript_pair_from_index(self._idx, tid1, tid2)

# %% ../nbs/002_transcript_data.ipynb #bdd798a6
from pathlib import Path

def register_transcripts(adata, td_or_path, reference_fasta=None):
    """
    Register transcript annotations with an AnnData object.

    This stores transcript data in adata.uns so it persists with the object
    and can be reconstructed after saving/loading from h5ad.

    Parameters
    ----------
    adata : AnnData
        Annotated data object to register transcripts with
    td_or_path : TranscriptData or str or Path
        Either a TranscriptData object or path to GTF file
    reference_fasta : str or Path, optional
        Path to reference FASTA file (only used if td_or_path is a path)

    Examples
    --------
    >>> # Register from existing TranscriptData
    >>> td = TranscriptData("annotations.gtf")
    >>> register_transcripts(adata, td)
    >>>
    >>> # Or register directly from GTF path
    >>> register_transcripts(adata, "annotations.gtf", "genome.fa")
    >>>
    >>> # Now save and reload - transcript data persists
    >>> adata.write_h5ad("my_data.h5ad")
    >>> adata2 = sc.read_h5ad("my_data.h5ad")
    >>> td2 = get_transcript_data(adata2)  # Reconstructs automatically
    """
    if isinstance(td_or_path, (str, Path)):
        adata.uns['_transcript_gtf'] = str(td_or_path)
        adata.uns['_transcript_fasta'] = str(reference_fasta) if reference_fasta else None
        td = TranscriptData(str(td_or_path), reference_fasta)
    else:
        td = td_or_path
        adata.uns['_transcript_gtf'] = td.gtf_file
        adata.uns['_transcript_fasta'] = td.reference_fasta

    adata.uns['transcript_data'] = td


def get_transcript_data(adata):
    """
    Get TranscriptData from an AnnData object.

    If the TranscriptData object is cached in adata.uns, returns it directly.
    Otherwise, reconstructs it from stored GTF/FASTA paths (useful after
    loading from h5ad).

    Parameters
    ----------
    adata : AnnData
        Annotated data object with registered transcript data

    Returns
    -------
    TranscriptData
        Transcript data object

    Raises
    ------
    ValueError
        If no transcript data is registered with this AnnData

    Examples
    --------
    >>> # After loading from h5ad
    >>> adata = sc.read_h5ad("my_data.h5ad")
    >>> td = get_transcript_data(adata)
    >>> exons = td.get_exons("ENSMUST00000070533")
    """
    # Check for cached object
    if 'transcript_data' in adata.uns and adata.uns['transcript_data'] is not None:
        return adata.uns['transcript_data']

    # Reconstruct from stored paths
    if '_transcript_gtf' in adata.uns:
        td = TranscriptData(
            adata.uns['_transcript_gtf'],
            adata.uns.get('_transcript_fasta')
        )
        adata.uns['transcript_data'] = td  # Cache for next call
        return td

    raise ValueError(
        "No transcript_data found in adata.uns. "
        "Register it first with: register_transcripts(adata, td)"
    )


# %% ../nbs/002_transcript_data.ipynb #8663c611
# Junctions — transcript/gene enumeration + isoform-specifics
# ===========================================================
from typing import List, Optional, Literal, Tuple, Iterable
import re
import numpy as np, pandas as pd

# ---------- core per-transcript junctions ----------
def _strand_char(s: int) -> str:
    return "+" if s == 1 else "-" if s == -1 else "."

def _junction_df_for_tx(rec: TxRecord) -> pd.DataFrame:
    """
    Build a tidy DataFrame of exon–exon junctions for a single transcript.
    Coordinates are introns as **1-based closed** [start,end] (between exons).
    Donor/acceptor are on the **transcript strand** (5' donor, 3' acceptor).
    """
    ex = rec.exons
    if ex.shape[0] <= 1:
        return pd.DataFrame(columns=[
            "chrom","strand","intron_start_1b","intron_end_1b",
            "donor_pos_1b","acceptor_pos_1b","gene_id","gene_name",
            "transcript_id","exon_i","exon_j","junction_id"
        ])

    up_end   = ex[:-1, 1].astype(np.int64)
    dn_start = ex[ 1:, 0].astype(np.int64)

    intron_start_1b = up_end + 1
    intron_end_1b   = dn_start - 1
    ok = intron_end_1b >= intron_start_1b
    if not np.any(ok):
        return pd.DataFrame(columns=[
            "chrom","strand","intron_start_1b","intron_end_1b",
            "donor_pos_1b","acceptor_pos_1b","gene_id","gene_name",
            "transcript_id","exon_i","exon_j","junction_id"
        ])

    up_end   = up_end[ok]
    dn_start = dn_start[ok]
    intron_start_1b = intron_start_1b[ok]
    intron_end_1b   = intron_end_1b[ok]

    if rec.strand == 1:
        donor_pos_1b    = up_end
        acceptor_pos_1b = dn_start
    else:
        donor_pos_1b    = dn_start
        acceptor_pos_1b = up_end

    exon_i = np.arange(1, ex.shape[0], dtype=np.int64)[ok]
    exon_j = exon_i + 1

    chrom    = np.full(intron_start_1b.shape, rec.chrom, dtype=object)
    strand_c = np.full(intron_start_1b.shape, _strand_char(rec.strand), dtype=object)
    gid      = np.full(intron_start_1b.shape, rec.gene_id if rec.gene_id else "", dtype=object)
    gnm      = np.full(intron_start_1b.shape, rec.gene_name if rec.gene_name else "", dtype=object)
    tid      = np.full(intron_start_1b.shape, rec.transcript_id, dtype=object)

    df = pd.DataFrame({
        "chrom": chrom,
        "strand": strand_c,
        "intron_start_1b": intron_start_1b.astype(np.int64),
        "intron_end_1b":   intron_end_1b.astype(np.int64),
        "donor_pos_1b":    donor_pos_1b.astype(np.int64),
        "acceptor_pos_1b": acceptor_pos_1b.astype(np.int64),
        "gene_id":         gid,
        "gene_name":       gnm,
        "transcript_id":   tid,
        "exon_i":          exon_i.astype(np.int64),
        "exon_j":          exon_j.astype(np.int64),
    })
    df["junction_id"] = (
        df["chrom"].astype(str) + ":" +
        df["intron_start_1b"].astype(str) + "-" +
        df["intron_end_1b"].astype(str) + ":" +
        df["strand"].astype(str)
    )
    # compact
    df["intron_start_1b"] = df["intron_start_1b"].astype("int32")
    df["intron_end_1b"]   = df["intron_end_1b"].astype("int32")
    df["donor_pos_1b"]    = df["donor_pos_1b"].astype("int32")
    df["acceptor_pos_1b"] = df["acceptor_pos_1b"].astype("int32")
    df["exon_i"]          = df["exon_i"].astype("int16")
    df["exon_j"]          = df["exon_j"].astype("int16")
    return df

def _collapse_identical_introns(df: pd.DataFrame) -> pd.DataFrame:
    """Deduplicate identical introns and collect supporting transcript IDs."""
    if df.empty:
        return df
    grp_cols = ["chrom","strand","intron_start_1b","intron_end_1b","gene_id","gene_name"]
    g = df.groupby(grp_cols, as_index=False, sort=False)
    out = g.agg({
        "donor_pos_1b":"first",
        "acceptor_pos_1b":"first",
        "transcript_id": lambda x: sorted(set(map(str, x))),
    }).rename(columns={"transcript_id":"supporting_transcripts"})
    out["n_transcripts"] = out["supporting_transcripts"].map(len).astype("int16")
    out["junction_id"] = (
        out["chrom"].astype(str) + ":" +
        out["intron_start_1b"].astype(str) + "-" +
        out["intron_end_1b"].astype(str) + ":" +
        out["strand"].astype(str)
    )
    return out

# ---------- public enumeration & exports ----------
def gene_junctions_df(idx: TranscriptIndex, gene_key: str, *, collapse: bool=False) -> pd.DataFrame:
    """
    Junctions for all transcripts of a gene (gene_id or gene_name).
    collapse=False → per-transcript rows
    collapse=True  → unique introns + supporting_transcripts
    """
    txs: List[str] = idx.transcripts_of_gene(gene_key)
    if not txs:
        # accept a transcript id as a 'gene_key' for convenience
        try:
            idx.tx(gene_key)
            txs = [gene_key]
        except Exception:
            return pd.DataFrame(columns=[
                "chrom","strand","intron_start_1b","intron_end_1b","donor_pos_1b","acceptor_pos_1b",
                "gene_id","gene_name","transcript_id","exon_i","exon_j","junction_id"
            ])
    parts = []
    for tid in txs:
        try:
            parts.append(_junction_df_for_tx(idx.tx(tid)))
        except KeyError:
            pass
    if not parts:
        return pd.DataFrame(columns=[
            "chrom","strand","intron_start_1b","intron_end_1b","donor_pos_1b","acceptor_pos_1b",
            "gene_id","gene_name","transcript_id","exon_i","exon_j","junction_id"
        ])
    df = pd.concat(parts, ignore_index=True)
    if collapse:
        df = _collapse_identical_introns(df)
        return df.sort_values(["chrom","intron_start_1b","intron_end_1b","strand"], kind="mergesort", ignore_index=True)
    else:
        return df.sort_values(["transcript_id","intron_start_1b"], kind="mergesort", ignore_index=True)

def _to_bed12_regtools(df: pd.DataFrame, name_field: str="junction_id", label_prefix: Optional[str]="JUNC") -> pd.DataFrame:
    """
    Minimal regtools-like BED12 for junctions using two 1bp blocks at intron edges.
    BED12 columns: chrom, start, end, name, score, strand, thickStart, thickEnd, itemRgb, blockCount, blockSizes, blockStarts
    """
    cols = ["chrom","start","end","name","score","strand","thickStart","thickEnd","itemRgb","blockCount","blockSizes","blockStarts"]
    if df.empty:
        return pd.DataFrame(columns=cols)

    start0 = (df["intron_start_1b"].astype(np.int64) - 1)
    end0   =  df["intron_end_1b"].astype(np.int64)

    name = df[name_field].astype(str) if name_field in df.columns else df["junction_id"].astype(str)
    if label_prefix:
        name = (label_prefix + ":" + name).astype(str)

    bed12 = pd.DataFrame({
        "chrom": df["chrom"].astype(str),
        "start": start0,
        "end":   end0,
        "name":  name,
        "score": 0,
        "strand": df["strand"].astype(str),
        "thickStart": start0,
        "thickEnd":   end0,
        "itemRgb": "0",
        "blockCount": 2,
        "blockSizes": "1,1",
        "blockStarts": "0," + (end0 - start0 - 1).astype(str),
    })
    for c in ("start","end","thickStart","thickEnd","blockCount","score"):
        bed12[c] = bed12[c].astype("int32")
    return bed12[cols]

def gene_junctions_bed12(
    idx: TranscriptIndex,
    gene_key: str,
    *,
    collapse: bool=True,
    name_style: Literal["junction_id","short","supporting"]="junction_id",
    label_prefix: Optional[str]="JUNC"
) -> pd.DataFrame:
    """
    Return a regtools-compatible BED12.
      collapse=True  → unique introns (default)
      name_style:
        - "junction_id": chrom:start-end:strand
        - "short": gene_name|gene_id:start-end:strand
        - "supporting": junction_id|n=k  (needs collapse=True)
    """
    df = gene_junctions_df(idx, gene_key, collapse=collapse)
    if df.empty:
        return _to_bed12_regtools(df)

    if name_style == "junction_id":
        name_col = "junction_id"
        use = df
    elif name_style == "short":
        gname = df.get("gene_name", pd.Series([""]*len(df))).fillna("")
        gid   = df.get("gene_id",   pd.Series([""]*len(df))).fillna("")
        base  = np.where(gname.values != "", gname.values, gid.values)
        name  = (pd.Series(base, dtype=str) + ":" +
                 df["intron_start_1b"].astype(str) + "-" +
                 df["intron_end_1b"].astype(str) + ":" +
                 df["strand"].astype(str))
        use = df.assign(_name=name)
        name_col = "_name"
    elif name_style == "supporting" and "n_transcripts" in df.columns:
        name = (df["junction_id"].astype(str) + "|n=" + df["n_transcripts"].astype(str))
        use = df.assign(_name=name)
        name_col = "_name"
    else:
        name_col = "junction_id"
        use = df

    return _to_bed12_regtools(use, name_field=name_col, label_prefix=label_prefix)

def write_gene_junctions_bed12(idx: TranscriptIndex, gene_key: str, out_path: str, **kwargs) -> None:
    """Write regtools-compatible BED12 to disk."""
    bed12 = gene_junctions_bed12(idx, gene_key, **kwargs)
    bed12.to_csv(out_path, sep="\t", header=False, index=False)

def gene_junctions_bed6(idx: TranscriptIndex, gene_key: str, *, collapse: bool=True, name_field: str="junction_id") -> pd.DataFrame:
    """Optional BED6 exporter."""
    df = gene_junctions_df(idx, gene_key, collapse=collapse)
    if df.empty:
        return pd.DataFrame(columns=["chrom","start","end","name","score","strand"])
    bed6 = pd.DataFrame({
        "chrom": df["chrom"].astype(str),
        "start": df["intron_start_1b"].astype(np.int64) - 1,
        "end":   df["intron_end_1b"].astype(np.int64),
        "name":  (df[name_field] if name_field in df.columns else df["junction_id"]).astype(str),
        "score": 0,
        "strand": df["strand"].astype(str),
    })
    bed6["start"] = bed6["start"].astype("int32")
    bed6["end"]   = bed6["end"].astype("int32")
    return bed6

# ---------- NEW: isoform-specific classification ----------
def classify_gene_junctions(idx: "TranscriptIndex", gene_key: str) -> pd.DataFrame:
    """
    Classify a gene's unique junctions into:
      - 'common'          : present in all transcripts
      - 'fully_unique'    : present in exactly one transcript
      - 'partially_unique': present in >1 but not all transcripts
    Returns one row per unique junction with supporting transcripts.
    """
    df = gene_junctions_df(idx, gene_key, collapse=True)
    if df.empty:
        return df.assign(classification=pd.Series(dtype=object))
    txs = idx.transcripts_of_gene(gene_key)
    n_gene_tx = max(1, len(txs))
    n_support = df["supporting_transcripts"].map(len).astype(int)
    cls = np.where(n_support == n_gene_tx, "common",
          np.where(n_support == 1, "fully_unique", "partially_unique"))
    out = df.assign(
        n_supporting=n_support.astype("int16"),
        n_gene_transcripts=np.int16(n_gene_tx),
        classification=cls.astype(str)
    )
    cat = pd.Categorical(out["classification"], ["fully_unique","partially_unique","common"], ordered=True)
    return (out.assign(_ord=cat)
               .sort_values(["_ord","chrom","intron_start_1b","intron_end_1b","strand"], kind="mergesort")
               .drop(columns=["_ord"])
               .reset_index(drop=True))

def isoform_specific_junctions(
    idx: "TranscriptIndex",
    gene_key: str,
    transcript_id: Optional[str] = None
) -> pd.DataFrame:
    """
    Return only 'fully_unique' junctions for the gene; if transcript_id is provided,
    keep only those tagging that transcript.
    """
    c = classify_gene_junctions(idx, gene_key)
    if c.empty:
        return c
    c = c[c["classification"] == "fully_unique"].copy()
    if transcript_id is not None:
        tid = re.sub(r"\.\d+$", "", str(transcript_id))
        c = c[c["supporting_transcripts"].map(lambda ts: any(re.sub(r"\.\d+$","",t)==tid for t in ts))].copy()
    # handy 0-based for joins
    c["start0"] = (c["intron_start_1b"].astype(np.int64) - 1).astype("int32")
    c["end0"]   = c["intron_end_1b"].astype("int32")
    return c

def choose_transcript_sentinels(idx: "TranscriptIndex", gene_key: str) -> pd.DataFrame:
    """
    Pick at least one fully-unique junction per transcript (sentinel).
    Heuristic: prefer the widest intron if multiple choices exist.
    """
    u = isoform_specific_junctions(idx, gene_key)
    if u.empty: return pd.DataFrame(columns=["transcript_id","chrom","start0","end0","strand","junction_id"])
    rows = []
    for _, r in u.iterrows():
        for tid in r["supporting_transcripts"]:
            rows.append({
                "transcript_id": tid,
                "chrom": r["chrom"],
                "start0": int(r["intron_start_1b"] - 1),
                "end0":   int(r["intron_end_1b"]),
                "strand": r["strand"],
                "junction_id": r["junction_id"],
                "width":  int(r["intron_end_1b"] - r["intron_start_1b"]),
            })
    df = pd.DataFrame(rows)
    if df.empty: return df
    return (df.sort_values(["transcript_id","width"], ascending=[True, False])
              .drop_duplicates(subset=["transcript_id"])
              .drop(columns=["width"])
              .reset_index(drop=True))

# ---------- regtools interop + "expressed-uniqueness" ----------
def read_regtools_bed12(path: str) -> pd.DataFrame:
    """
    Read a BED12 (or BED6) junction file (e.g., regtools `junctions extract`).
    Returns columns: chrom,start0,end0,strand,count (score used when present).
    """
    cols12 = ["chrom","start","end","name","score","strand","thickStart","thickEnd","itemRgb","blockCount","blockSizes","blockStarts"]
    df = pd.read_csv(path, sep="\t", header=None, comment="#")
    if df.shape[1] >= 12:
        df = df.iloc[:, :12]; df.columns = cols12
    elif df.shape[1] >= 6:
        df = df.iloc[:, :6];  df.columns = cols12[:6]
    else:
        raise ValueError("BED must have at least 6 columns.")
    out = pd.DataFrame({
        "chrom":  df["chrom"].astype(str),
        "start0": df["start"].astype("int64").astype("int32"),
        "end0":   df["end"].astype("int64").astype("int32"),
        "strand": df["strand"].astype(str)
    })
    if "score" in df.columns:
        with np.errstate(all="ignore"):
            cnt = pd.to_numeric(df["score"], errors="coerce")
        out["count"] = cnt.fillna(0).astype("int32")
    else:
        out["count"] = 0
    return out

def _norm_chr(s: pd.Series) -> pd.Series:
    x = s.astype(str)
    return x.str.replace(r"^chr(?=\w)", "", regex=True)

def match_counts_to_unique(
    unique_df: pd.DataFrame,
    counts_df: pd.DataFrame,
    min_count: int = 1
) -> pd.DataFrame:
    """
    Left-join observed counts onto the 'fully_unique' junctions by (chrom,start0,end0,strand).
    Filter to expressed sentinels (count >= min_count).
    """
    if unique_df.empty:
        return unique_df
    left = unique_df.copy()
    right = counts_df.copy()
    left["_chr_norm"]  = _norm_chr(left["chrom"])
    right["_chr_norm"] = _norm_chr(right["chrom"])
    m = left.merge(
        right.rename(columns={"chrom":"chrom_obs"})[["_chr_norm","start0","end0","strand","count"]],
        how="left", on=["_chr_norm","start0","end0","strand"]
    ).drop(columns=["_chr_norm"])
    m["count"] = m["count"].fillna(0).astype("int32")
    return m[m["count"] >= int(min_count)].copy()

def isoform_specific_among_expressed(
    idx: "TranscriptIndex",
    gene_key: str,
    counts_df: pd.DataFrame,
    *,
    min_count: int = 1
) -> pd.DataFrame:
    """
    Practical variant: compute 'fully unique' **among expressed transcripts** only.
    A transcript is considered expressed if ANY of its per-transcript junctions has count ≥ min_count.
    """
    # per-transcript junctions
    per_tx = gene_junctions_df(idx, gene_key, collapse=False)
    if per_tx.empty:
        return per_tx.iloc[:0].copy()

    # observed junctions set
    obs = counts_df.copy()
    if obs.empty:
        return per_tx.iloc[:0].copy()
    obs["_chr_norm"] = _norm_chr(obs["chrom"])
    obs_key = set(zip(obs["_chr_norm"], obs["start0"].astype(int), obs["end0"].astype(int), obs["strand"].astype(str)))

    # mark transcripts that have at least one observed junction
    per_tx["_chr_norm"] = _norm_chr(per_tx["chrom"])
    per_tx["start0"] = per_tx["intron_start_1b"].astype(int) - 1
    per_tx["end0"]   = per_tx["intron_end_1b"].astype(int)
    per_tx["key"] = list(zip(per_tx["_chr_norm"], per_tx["start0"], per_tx["end0"], per_tx["strand"].astype(str)))
    tx_expressed = (per_tx.groupby("transcript_id")["key"]
                         .apply(lambda ks: any(k in obs_key for k in ks))
                         .to_dict())

    expressed_txs = {t for t, ok in tx_expressed.items() if ok}
    if not expressed_txs:
        return per_tx.iloc[:0].copy()

    # collapse unique junctions and re-evaluate support only among expressed txs
    uniq = _collapse_identical_introns(per_tx.drop(columns=["_chr_norm","start0","end0","key"]))
    def _support_expressed(ts: Iterable[str]) -> list[str]:
        return sorted([t for t in ts if t in expressed_txs])
    uniq["supporting_transcripts_expressed"] = uniq["supporting_transcripts"].map(_support_expressed)
    uniq["n_supporting_expressed"] = uniq["supporting_transcripts_expressed"].map(len).astype("int16")

    # keep those unique among expressed (exactly one)
    out = uniq[uniq["n_supporting_expressed"] == 1].copy()
    out["start0"] = (out["intron_start_1b"].astype(int) - 1).astype("int32")
    out["end0"]   = out["intron_end_1b"].astype("int32")
    return out.reset_index(drop=True)
