"""This module retrieves genomic coordinates and other key information related to transcripts from a GTF file. Using **pyRanges**, it efficiently stores and visualizes transcript features like exons, CDS, and UTRs."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/002_transcript_data.ipynb.

# %% auto 0
__all__ = ['TxRecord', 'TranscriptIndex', 'TranscriptData']

# %% ../nbs/002_transcript_data.ipynb 3
import pandas as pd
from typing import List, Tuple, Dict, Optional
from functools import lru_cache
import pyranges as pr
from pyfaidx import Fasta
import logging
import re
from typing import Any, Dict, Union


# %% ../nbs/002_transcript_data.ipynb 4
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple
import os, pathlib, pickle, hashlib, re
import numpy as np
import pandas as pd
import pyranges as pr

def _versionless(tid: str) -> str:
    i = tid.rfind(".")
    return tid[:i] if i > 0 and tid[i + 1:].isdigit() else tid

@dataclass(frozen=True, slots=True)
class TxRecord:
    transcript_id: str
    gene_id: Optional[str]
    gene_name: Optional[str]
    transcript_name: Optional[str]
    transcript_type: Optional[str]
    chrom: str
    strand: int  # +1 / -1
    span: Tuple[int, int]  # (min_start, max_end)
    exons: np.ndarray      # (n,2) int32 [[Start,End],...]
    cds: np.ndarray
    utr5: np.ndarray
    utr3: np.ndarray

    @property
    def junctions(self) -> np.ndarray:
        if self.exons.shape[0] <= 1:
            return np.empty((0, 2), dtype=np.int32)
        ends, starts = self.exons[:-1, 1], self.exons[1:, 0]
        return np.stack([ends, starts], axis=1).astype(np.int32)

# %%
class TranscriptIndex:
    """Fast, read-only index built from a GTF/GFF. O(1) lookups for blocks & metadata."""

    def __init__(self, tx_by_id: Dict[str, TxRecord], gene_to_tx: Dict[str, List[str]],
                 genename_to_tx: Dict[str, List[str]], cache_key: str):
        self._tx_by_id = tx_by_id
        self._gene_to_tx = gene_to_tx
        self._genename_to_tx = genename_to_tx
        self._cache_key = cache_key

        # Versionless alias map (match ENST… to ENST….7)
        self._tx_by_id_novers: Dict[str, TxRecord] = {}
        for tid, rec in tx_by_id.items():
            base = re.sub(r"\.\d+$", "", tid)
            self._tx_by_id_novers.setdefault(base, rec)

    # ---------------------------------------------------------------------
    @classmethod
    def build(cls, gtf_path: str, cache_dir: Optional[str] = None, *,
              keep_features: Tuple[str, ...] = ("exon", "CDS", "5UTR", "3UTR"),
              protein_coding_only: bool = False,
              keep_chroms: Optional[Tuple[str, ...]] = None) -> "TranscriptIndex":

        gtf_path = str(pathlib.Path(gtf_path).resolve())

        salt = f".pc{int(protein_coding_only)}.kf{hashlib.sha1(','.join(keep_features).encode()).hexdigest()[:6]}"
        if keep_chroms:
            salt += f".kc{hashlib.sha1(','.join(keep_chroms).encode()).hexdigest()[:6]}"

        key = cls._cache_key(gtf_path) + salt
        cache_file = (os.path.join(cache_dir, f"txindex.{key}.pkl") if cache_dir else None)

        if cache_file and os.path.exists(cache_file):
            with open(cache_file, "rb") as f:
                return pickle.load(f)

        # 1) Load & normalize schema
        df = pr.read_gtf(gtf_path).df

        # Column normalization
        desired = ["Feature","Chromosome","Start","End","Strand",
                   "gene_id","gene_name","transcript_id",
                   "transcript_name","transcript_type"]

        if "transcript_type" not in df.columns and "transcript_biotype" in df.columns:
            df["transcript_type"] = df["transcript_biotype"]

        for c in desired:
            if c not in df.columns:
                df[c] = pd.NA

        df = df[desired].copy()

        # Normalize UTR labels
        df["Feature"] = df["Feature"].replace({
            "five_prime_UTR": "5UTR",
            "three_prime_UTR": "3UTR"
        })

        # Optional filters
        if keep_chroms is not None:
            df = df[df["Chromosome"].isin(keep_chroms)]
        if protein_coding_only and "transcript_type" in df.columns:
            df = df[df["transcript_type"] == "protein_coding"]

        df = df[df["Feature"].isin(keep_features)]

        # Dtypes
        df["Start"] = pd.to_numeric(df["Start"], errors="coerce").astype("Int64").astype("float64").astype("int32", errors="ignore")
        df["End"] = pd.to_numeric(df["End"], errors="coerce").astype("Int64").astype("float64").astype("int32", errors="ignore")
        df["strand_int"] = df["Strand"].map({"+": 1, "-": -1}).astype("Int8").fillna(0).astype("int8")

        if df.empty or df["transcript_id"].isna().all():
            raise RuntimeError(f"No transcript rows retained for {gtf_path}. Check file, species, or filters.")
        # 2) Global stable sort
        df.sort_values(["transcript_id", "Start", "End"],
                       kind="mergesort", inplace=True, ignore_index=True)

        # 3) Factorize per-transcript slices
        tid_codes, tid_uniques = pd.factorize(df["transcript_id"].astype(str), sort=False)
        change = np.r_[True, tid_codes[1:] != tid_codes[:-1], True]
        bounds = np.flatnonzero(change)
        starts, ends = bounds[:-1], bounds[1:]

        # Column numpy views
        feat = df["Feature"].to_numpy()
        chrom = df["Chromosome"].astype(str).to_numpy()
        start = df["Start"].to_numpy()
        end = df["End"].to_numpy()
        strand_int = df["strand_int"].to_numpy()
        gene_id = df["gene_id"].astype(str).to_numpy()
        gene_name = df["gene_name"].astype(str).to_numpy()
        tx_name = df["transcript_name"].astype(str).to_numpy()
        tx_type = df["transcript_type"].astype(str).to_numpy()

        # Feature masks
        f_exon = (feat == "exon")
        f_cds = (feat == "CDS")
        f_u5 = (feat == "5UTR")
        f_u3 = (feat == "3UTR")

        def _blocks_slice(i0: int, i1: int, mask: np.ndarray) -> np.ndarray:
            if i1 <= i0:
                return np.empty((0, 2), np.int32)
            loc = np.nonzero(mask[i0:i1])[0]
            if loc.size == 0:
                return np.empty((0, 2), np.int32)
            s = start[i0 + loc]
            e = end[i0 + loc]
            out = np.empty((loc.size, 2), dtype=np.int32)
            out[:, 0] = s
            out[:, 1] = e
            return out

        def _first_non_empty(a: np.ndarray) -> Optional[str]:
            for v in a:
                if v and v != "nan":
                    return str(v)
            return None

        tx_by_id: Dict[str, TxRecord] = {}
        gene_to_tx: Dict[str, List[str]] = {}
        genename_to_tx: Dict[str, List[str]] = {}

        for code, i0, i1 in zip(range(len(starts)), starts, ends):
            tid = str(tid_uniques[code])
            chrom0 = chrom[i0]
            sgn = int(strand_int[i0]) if strand_int[i0] in (1, -1) else 0
            gid = _first_non_empty(gene_id[i0:i1])
            gnm = _first_non_empty(gene_name[i0:i1])
            tnm = _first_non_empty(tx_name[i0:i1])
            ttp = _first_non_empty(tx_type[i0:i1])

            # guard against NaN starts/ends
            s_min = start[i0:i1][~np.isnan(start[i0:i1])]
            e_max = end[i0:i1][~np.isnan(end[i0:i1])]
            if s_min.size == 0 or e_max.size == 0:
                continue

            rec = TxRecord(
                transcript_id=tid,
                gene_id=gid,
                gene_name=gnm,
                transcript_name=tnm,
                transcript_type=ttp,
                chrom=chrom0,
                strand=sgn,
                span=(int(np.min(s_min)), int(np.max(e_max))),
                exons=_blocks_slice(i0, i1, f_exon),
                cds=_blocks_slice(i0, i1, f_cds),
                utr5=_blocks_slice(i0, i1, f_u5),
                utr3=_blocks_slice(i0, i1, f_u3),
            )

            tx_by_id[tid] = rec
            if gid:
                gene_to_tx.setdefault(gid, []).append(tid)
            if gnm:
                genename_to_tx.setdefault(gnm, []).append(tid)

        idx = cls(tx_by_id, gene_to_tx, genename_to_tx, key)

        # refuse to cache an empty index
        if cache_dir:
            if len(tx_by_id) == 0:
                raise RuntimeError("TranscriptIndex built empty — refusing to cache. Check GTF and filters.")
            os.makedirs(cache_dir, exist_ok=True)
            with open(cache_file, "wb") as f:
                pickle.dump(idx, f, protocol=pickle.HIGHEST_PROTOCOL)

        return idx

    # --------- version-tolerant lookups ---------
    def _resolve(self, tid: str) -> TxRecord:
        if tid in self._tx_by_id:
            return self._tx_by_id[tid]
        base = re.sub(r"\.\d+$", "", tid)
        rec = self._tx_by_id_novers.get(base)
        if rec is None:
            raise KeyError(tid)
        return rec

    def tx(self, tid: str) -> TxRecord:
        return self._resolve(tid)

    def exons(self, tid: str) -> np.ndarray:
        return self._resolve(tid).exons

    def cds(self, tid: str) -> np.ndarray:
        return self._resolve(tid).cds

    def utr5(self, tid: str) -> np.ndarray:
        return self._resolve(tid).utr5

    def utr3(self, tid: str) -> np.ndarray:
        return self._resolve(tid).utr3

    def junctions(self, tid: str) -> np.ndarray:
        return self._resolve(tid).junctions

    def chrom(self, tid: str) -> str:
        return self._resolve(tid).chrom

    def strand(self, tid: str) -> int:
        return self._resolve(tid).strand

    def span(self, tid: str) -> Tuple[int, int]:
        return self._resolve(tid).span

    def transcripts_of_gene(self, key: str) -> List[str]:
        return self._gene_to_tx.get(key, self._genename_to_tx.get(key, []))

    # --------- small debuggers ---------
    def summary(self) -> Dict[str, object]:
        return {
            "n_transcripts": len(self._tx_by_id),
            "n_genes_by_id": len(self._gene_to_tx),
            "n_genes_by_name": len(self._genename_to_tx),
            "cache_key": self._cache_key,
        }

    def list_transcripts(self, n: int = 10, prefix: Optional[str] = None) -> List[str]:
        ids = list(self._tx_by_id.keys())
        if prefix:
            ids = [t for t in ids if t.startswith(prefix)]
        return ids[:n]

    @staticmethod
    def _cache_key(gtf_path: str) -> str:
        st = pathlib.Path(gtf_path).stat()
        return hashlib.sha1(f"{gtf_path}|{st.st_size}|{int(st.st_mtime)}".encode()).hexdigest()[:16]


# %% ../nbs/002_transcript_data.ipynb 5
from typing import List, Optional, Tuple
import numpy as np
import pandas as pd
import pyranges as pr

class TranscriptData:
    """Fast, drop-in replacement for your old TranscriptData, backed by TranscriptIndex."""

    def __init__(self, gtf_file: str, reference_fasta: Optional[str]=None, cache_dir: Optional[str]=None):
        self.gtf_file = gtf_file
        self.reference_fasta = reference_fasta
        self._idx = TranscriptIndex.build(gtf_file, cache_dir=cache_dir)

    def _wrap(self, tid:str, arr:np.ndarray, feature:str)->pr.PyRanges:
        if arr.size==0:
            return pr.PyRanges(pd.DataFrame(columns=["Chromosome","Start","End","Strand","Feature"]))
        chrom=self._idx.chrom(tid)
        strand="+" if self._idx.strand(tid)==1 else "-"
        df=pd.DataFrame({"Chromosome":chrom,"Start":arr[:,0],"End":arr[:,1],"Strand":strand})
        df["Feature"]=feature
        return pr.PyRanges(df)

    def get_exons(self, tid:str)->pr.PyRanges:
        return self._wrap(tid,self._idx.exons(tid),"exon")

    def get_cds(self, tid:str)->pr.PyRanges:
        return self._wrap(tid,self._idx.cds(tid),"CDS")

    def get_utr(self, tid:str, utr_type:str=None)->pr.PyRanges:
        if utr_type=="5UTR":
            return self._wrap(tid,self._idx.utr5(tid),"5UTR")
        if utr_type=="3UTR":
            return self._wrap(tid,self._idx.utr3(tid),"3UTR")
        a5,a3=self._idx.utr5(tid),self._idx.utr3(tid)
        parts=[]
        if a5.size: parts.append(self._wrap(tid,a5,"5UTR").df)
        if a3.size: parts.append(self._wrap(tid,a3,"3UTR").df)
        return pr.PyRanges(pd.concat(parts,ignore_index=True)) if parts else self._wrap(tid,np.empty((0,2),np.int32),"UTR")

    def get_intron_ranges(self, tid:str)->pr.PyRanges:
        ex=self._idx.exons(tid)
        if ex.shape[0]<=1:
            return pr.PyRanges(pd.DataFrame(columns=["Chromosome","Start","End","Strand"]))
        intr=np.stack([ex[:-1,1],ex[1:,0]],axis=1)
        chrom=self._idx.chrom(tid)
        strand="+" if self._idx.strand(tid)==1 else "-"
        df=pd.DataFrame({"Chromosome":chrom,"Start":intr[:,0],"End":intr[:,1],"Strand":strand})
        return pr.PyRanges(df)

    def get_exon_coords_and_strand(self, tid:str)->Tuple[List[List[int]],Optional[int]]:
        ex=self._idx.exons(tid)
        strand=self._idx.strand(tid)
        coords=[[int(e),int(s)] for s,e in ex]
        return coords,strand

    def get_transcript_length(self, tid:str)->int:
        ex=self._idx.exons(tid)
        return int(np.maximum(0,ex[:,1]-ex[:,0]).sum()) if ex.size else 0

    def get_chromosome(self, tid:str)->Optional[str]:
        return self._idx.chrom(tid)

    def get_strand(self, tid:str)->Optional[int]:
        return self._idx.strand(tid)

    def get_transcripts_by_gene_id(self, gid:str)->List[str]:
        return self._idx.transcripts_of_gene(gid)

    def get_transcripts_by_gene_name(self, gnm:str)->List[str]:
        return self._idx.transcripts_of_gene(gnm)

    # quick access to numpy arrays for plotting
    def arrays(self, tid:str)->dict:
        return {
            "chrom":self._idx.chrom(tid),
            "strand":self._idx.strand(tid),
            "span":self._idx.span(tid),
            "exons":self._idx.exons(tid),
            "cds":self._idx.cds(tid),
            "utr5":self._idx.utr5(tid),
            "utr3":self._idx.utr3(tid),
            "junctions":self._idx.junctions(tid)
        }
    def get_exon_coords_and_strand_batch_fast(self, transcript_ids: tuple[str, ...]):
        """
        Return {tid: (exons_as_[ [end,start], ... ], strand_int)} for many IDs at once.
        Uses the in-memory arrays directly (no pandas).
        """
        out = {}
        idx = self._idx
        for tid in transcript_ids:
            ex = idx.exons(tid)  # [[Start,End]] int32
            st = idx.strand(tid) # +1 / -1
            if ex.size:
                arr = np.empty_like(ex)
                arr[:, 0] = ex[:, 1]  # end
                arr[:, 1] = ex[:, 0]  # start
                ex_ls = arr.tolist()
            else:
                ex_ls = []
            out[tid] = (ex_ls, st)
        return out

    def get_cds_bounds_batch_fast(self, transcript_ids: tuple[str, ...]):
        """
        Return {tid: (cds_start, cds_end) or None} for many IDs at once.
        """
        out = {}
        idx = self._idx
        for tid in transcript_ids:
            cds = idx.cds(tid)
            if cds.size:
                out[tid] = (int(cds[:,0].min()), int(cds[:,1].max()))
            else:
                out[tid] = None
        return out

    def get_transcript_info(self, transcript_id: str) -> dict:
        """
        Fast version that doesn’t touch pandas; mirrors your old shape.
        Now includes gene_name and gene_id so plotting can resolve the gene label.
        """
        tid = _versionless(transcript_id)
        rec = self._idx.tx(tid)
        cds = self._idx.cds(tid)
        return {
            "transcript_id": rec.transcript_id,
            "transcript_name": rec.transcript_name or "unknown",
            "transcript_type": rec.transcript_type or "unknown",
            "gene_id": rec.gene_id,
            "gene_name": rec.gene_name,
            "cds_start": int(cds[:,0].min()) if cds.size else None,
            "cds_end": int(cds[:,1].max()) if cds.size else None,
            "chromosome": rec.chrom,
            "strand": "+" if rec.strand == 1 else "-"
        }
