"""The TranscriptPlots class is defined to facilitate the visualization of transcript structures."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/001_transcript_plots.ipynb.

# %% auto 0
__all__ = ['merge_intervals', 'TranscriptPlots']

# %% ../nbs/001_transcript_plots.ipynb 3
import numpy as np
import requests
import sys
import matplotlib.pyplot as plt


# %% ../nbs/001_transcript_plots.ipynb 7
# ==========================================================
# TranscriptPlots — polished labels + optional ct color bands
# ==========================================================

from typing import List, Optional, Tuple, Sequence
import importlib, math, textwrap, re
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
import matplotlib.colors as mcolors
from matplotlib.ticker import MaxNLocator, FuncFormatter

_DEFAULT_COLORS = ['blue', 'green', 'orange', 'purple', 'brown']
_UI_GREY = "#555555"  # connectors, arrows, length bars, locus ruler

# ---------- small utilities ----------
def merge_intervals(intervals: List[Tuple[int, int]]):
    if not intervals:
        return []
    intervals = sorted(([min(a, b), max(a, b)] for a, b in intervals), key=lambda x: x[0])
    out = [intervals[0]]
    for s, e in intervals[1:]:
        ps, pe = out[-1]
        if s <= pe:
            out[-1][1] = max(pe, e)
        else:
            out.append([s, e])
    return out

def _versionless(tid: str) -> str:
    i = tid.rfind(".")
    return tid[:i] if i > 0 and tid[i + 1:].isdigit() else tid

def _soft_wrap(label: str, width: int, max_lines: int = 3) -> list[str]:
    if width <= 0 or len(label) <= width:
        return [label]
    lines = textwrap.wrap(label, width=width, break_long_words=False, break_on_hyphens=True)
    if len(lines) > max_lines:
        head = lines[:max_lines-1]
        tail = " ".join(lines[max_lines-1:])
        head.append(textwrap.shorten(tail, width=max(6, width), placeholder="…"))
        lines = head
    return lines

def _fit_font_for_columns(n_cols: int, panel_w: float, avg_chars: float,
                          *, min_fs=7, max_fs=11, rotate_threshold=10) -> tuple[int, int, int]:
    # Heuristic: rotation/size/wrap based on column count
    if n_cols > rotate_threshold:
        rot = 35
        fs = max(min_fs, int(max_fs - 0.35*(n_cols-rotate_threshold)))
        wrap = max(10, int(avg_chars*0.9))
    else:
        rot = 0
        fs = min(max_fs, int(max_fs - 0.15*(n_cols-3)))
        wrap = 16
    fs = min(max_fs, max(min_fs, fs))
    return rot, fs, wrap


from typing import List, Optional, Tuple, Sequence
import importlib, textwrap, re
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
import matplotlib.colors as mcolors
from matplotlib.ticker import MaxNLocator, FuncFormatter

def merge_intervals(intervals: List[Tuple[int, int]]):
    if not intervals:
        return []
    intervals = sorted(([min(a, b), max(a, b)] for a, b in intervals), key=lambda x: x[0])
    out = [intervals[0]]
    for s, e in intervals[1:]:
        ps, pe = out[-1]
        if s <= pe:
            out[-1][1] = max(pe, e)
        else:
            out.append([s, e])
    return out

def _versionless(tid: str) -> str:
    i = tid.rfind(".")
    return tid[:i] if i > 0 and tid[i + 1:].isdigit() else tid

def _soft_wrap(label: str, width: int, max_lines: int = 3) -> list[str]:
    if width <= 0 or len(label) <= width:
        return [label]
    lines = textwrap.wrap(label, width=width, break_long_words=False, break_on_hyphens=True)
    if len(lines) > max_lines:
        head = lines[:max_lines-1]
        tail = " ".join(lines[max_lines-1:])
        head.append(textwrap.shorten(tail, width=max(6, width), placeholder="…"))
        lines = head
    return lines

def _fit_font_for_columns(n_cols: int, panel_w: float, avg_chars: float,
                          *, min_fs=7, max_fs=11, rotate_threshold=10) -> tuple[int, int, int]:
    # Heuristic: rotation/size/wrap based on column count
    if n_cols > rotate_threshold:
        rot = 35
        fs = max(min_fs, int(max_fs - 0.35*(n_cols-rotate_threshold)))
        wrap = max(10, int(avg_chars*0.9))
    else:
        rot = 0
        fs = min(max_fs, int(max_fs - 0.15*(n_cols-3)))
        wrap = 16
    fs = min(max_fs, max(min_fs, fs))
    return rot, fs, wrap

_DEFAULT_COLORS = ['blue', 'green', 'orange', 'purple', 'brown']
_UI_GREY = "#555555"  # connectors, arrows, length bars, locus ruler

class TranscriptPlots:
    """
    Visualize transcripts with intron compression and optional right-side panels.
    Upgrades: bulletproof column labels, optional cell-type color band, tidy colorbar.
    """

    # right-panel geometry
    panel_x0: float = 1.08
    panel_pad: float = 0.02
    panel_width: float = 0.32

    # row geometry
    row_pitch: float = 0.60
    exon_height: float = 0.22
    top_margin: float = 0.30
    bottom_margin: float = 0.20

    def __init__(self, gtf_file: Optional[str] = None, reference_fasta: Optional[str] = None, *,
                 transcript_data=None,
                 # intron scaling
                 intron_scale: float = 0.1, intron_scale_mode: str = 'relative', intron_fixed_length: float = 5.0,
                 # exon scaling
                 exon_scale_mode: str = 'none', exon_scale: float = 1.0, exon_fixed_length: float = 8.0,
                 # visual safeties
                 exon_min_length: float = 1.5, intron_min_length: float = 1.0,
                 # labels/length bars
                 label_drop: float = 0.1, show_length: bool = True, length_mode: str = 'exonic'):
        """
        show_length: draw a per-row length bar (True/False)
        length_mode: 'exonic' | 'genomic'
        """
        self.colors = list(_DEFAULT_COLORS)

        # introns
        self.intron_scale = float(intron_scale)
        self.intron_scale_mode = intron_scale_mode
        self.intron_fixed_length = float(intron_fixed_length)

        # exons
        self.exon_scale_mode = exon_scale_mode
        self.exon_scale = float(exon_scale)
        self.exon_fixed_length = float(exon_fixed_length)

        # minimum segment widths
        self.exon_min_length = float(exon_min_length)
        self.intron_min_length = float(intron_min_length)

        # labels & bars
        self.label_drop = float(label_drop)
        self.show_length = bool(show_length)
        self.length_mode = length_mode

        # Obtain TranscriptData
        self.transcript_data = transcript_data
        if self.transcript_data is None and gtf_file is not None:
            TD = None
            for mod in ("allos.transcript_data", ".transcript_data", "transcript_data"):
                try:
                    TD = getattr(importlib.import_module(mod, package=__package__), "TranscriptData")
                    break
                except Exception:
                    continue
            if TD is None:
                raise ModuleNotFoundError(
                    "Could not import TranscriptData. Tried 'allos.transcript_data', "
                    "'.transcript_data', and 'transcript_data'."
                )
            self.transcript_data = TD(gtf_file=gtf_file, reference_fasta=reference_fasta)

        if self.transcript_data is None:
            raise RuntimeError("Provide transcript_data=... or gtf_file=...")

    # ---------- small utilities ----------
    @staticmethod
    def _merge_intervals(intervals: List[Tuple[int, int]]):
        if not intervals:
            return []
        intervals = sorted(([min(a, b), max(a, b)] for a, b in intervals), key=lambda x: x[0])
        out = [intervals[0]]
        for s, e in intervals[1:]:
            ps, pe = out[-1]
            if s <= pe:
                out[-1][1] = max(pe, e)
            else:
                out.append([s, e])
        return out

    @staticmethod
    def _versionless(tid: str) -> str:
        i = tid.rfind(".")
        return tid[:i] if i > 0 and tid[i + 1:].isdigit() else tid

    @staticmethod
    def _soft_wrap(label: str, width: int, max_lines: int = 3) -> list[str]:
        if width <= 0 or len(label) <= width:
            return [label]
        lines = textwrap.wrap(label, width=width, break_long_words=False, break_on_hyphens=True)
        if len(lines) > max_lines:
            head = lines[:max_lines-1]
            tail = " ".join(lines[max_lines-1:])
            head.append(textwrap.shorten(tail, width=max(6, width), placeholder="…"))
            lines = head
        return lines

    @staticmethod
    def _fit_font_for_columns(n_cols: int, panel_w: float, avg_chars: float,
                              *, min_fs=7, max_fs=11, rotate_threshold=10) -> tuple[int, int, int]:
        # Heuristic: rotation/size/wrap based on column count
        if n_cols > rotate_threshold:
            rot = 35
            fs = max(min_fs, int(max_fs - 0.35*(n_cols-rotate_threshold)))
            wrap = max(10, int(avg_chars*0.9))
        else:
            rot = 0
            fs = min(max_fs, int(max_fs - 0.15*(n_cols-3)))
            wrap = 16
        fs = min(max_fs, max(min_fs, fs))
        return rot, fs, wrap

    # ---------------- data access ----------------
    def _get_exons_and_strand(self, tid: str):
        return self.transcript_data.get_exon_coords_and_strand(self._versionless(tid))

    def _get_cds_bounds(self, tid: str):
        info = self.transcript_data.get_transcript_info(self._versionless(tid))
        cs, ce = info.get("cds_start"), info.get("cds_end")
        return (cs, ce) if (cs is not None and ce is not None) else None

    # ---------------- mapping helpers ----------------
    def _make_global_mapping(self, exons_lists):
        """
        Build a monotonic piecewise-linear mapper f: genomic -> [0,1] with:
        - intron compression (relative/fixed)
        - optional exon scaling (relative/fixed)
        """
        intervals = []
        for exs in exons_lists:
            for a, b in exs:
                s, e = (min(a, b), max(a, b))
                intervals.append([s, e])
        U = np.asarray(self._merge_intervals(intervals), dtype=np.int64)
        if U.size == 0:
            raise ValueError("No exonic intervals!")

        g0, g1 = int(U[0, 0]), int(U[-1, 1])
        exon_starts = U[:, 0].astype(np.int64)
        exon_ends = U[:, 1].astype(np.int64)
        exon_L = (exon_ends - exon_starts).astype(float)

        gap_starts = exon_ends[:-1]
        gap_ends = exon_starts[1:]
        gap_L = (gap_ends - gap_starts).astype(float)

        # Exon scaling
        if self.exon_scale_mode == 'relative':
            exon_scaled = np.maximum(exon_L * self.exon_scale, self.exon_min_length)
            exon_slope = exon_scaled / np.maximum(exon_L, 1e-9)
        elif self.exon_scale_mode == 'fixed':
            exon_scaled = np.maximum(np.full_like(exon_L, self.exon_fixed_length, dtype=float), self.exon_min_length)
            exon_slope = exon_scaled / np.maximum(exon_L, 1e-9)
        else:  # 'none'
            exon_scaled = np.maximum(exon_L, self.exon_min_length)
            exon_slope = exon_scaled / np.maximum(exon_L, 1e-9)

        # Intron scaling
        if gap_L.size:
            if self.intron_scale_mode == 'relative':
                gap_scaled = np.maximum(gap_L * self.intron_scale, self.intron_min_length)
                gap_slope = gap_scaled / np.maximum(gap_L, 1e-9)
            else:  # 'fixed'
                gap_scaled = np.maximum(np.full_like(gap_L, self.intron_fixed_length, dtype=float), self.intron_min_length)
                gap_slope = gap_scaled / np.maximum(gap_L, 1e-9)
        else:
            gap_scaled = np.array([], dtype=float)
            gap_slope = np.array([], dtype=float)

        # Alternating segments
        seg_starts = []; seg_ends = []; seg_slope = []; seg_is_exon = []
        for i in range(len(exon_L)):
            seg_starts.append(exon_starts[i]); seg_ends.append(exon_ends[i])
            seg_slope.append(exon_slope[i]); seg_is_exon.append(True)
            if i < len(gap_L):
                seg_starts.append(gap_starts[i]); seg_ends.append(gap_ends[i])
                seg_slope.append(gap_slope[i]); seg_is_exon.append(False)

        seg_starts = np.asarray(seg_starts, dtype=np.int64)
        seg_ends = np.asarray(seg_ends, dtype=np.int64)
        seg_slope = np.asarray(seg_slope, dtype=float)
        seg_len = (seg_ends - seg_starts).astype(float)
        seg_scaled = seg_len * seg_slope
        prefix_scaled = np.concatenate(([0.0], np.cumsum(seg_scaled)))
        total_scaled = prefix_scaled[-1] or 1.0
        ends_for_search = seg_ends

        def raw(x_arr):
            x_arr = np.asarray(x_arr, dtype=float)
            idx = np.searchsorted(ends_for_search, x_arr, side="right")
            idx = np.minimum(idx, len(seg_ends) - 1)
            start = seg_starts[idx].astype(float)
            end = seg_ends[idx].astype(float)
            slope = seg_slope[idx]
            x_clamped = np.minimum(np.maximum(x_arr, start), end)
            scaled = prefix_scaled[idx] + slope * (x_clamped - start)
            return scaled

        f = lambda x: float(raw(np.array([x]))[0] / total_scaled)
        return f, (g0, g1)

    # ---------------- rows & axes ----------------
    def _row_centers(self, n_rows: int) -> list[float]:
        return [-(i * self.row_pitch) for i in range(n_rows)]

    def _prep_axes(self, n_rows: int, *, reserve_panel_space: bool):
        plt.close('all')
        fig, ax = plt.subplots(figsize=(20, max(2, n_rows * 2)))
        ax.set_xlim(-0.05, self.panel_x0 + self.panel_width + self.panel_pad if reserve_panel_space else 1.05)
        ycs = self._row_centers(n_rows)
        y_top = self.top_margin
        y_bottom = (ycs[-1] - self.row_pitch / 2) - self.bottom_margin
        ax.set_ylim(y_bottom, y_top)
        ax.margins(0.0)
        ax.axis('off')
        return fig, ax, ycs

    # ---------------- draw one row ----------------
    def _draw_one(self, exons_e_s, strand, color, tid_label, mapper, y_center, cds_bounds,
                  *, show_row_bounds: bool, length_bar: Optional[dict]):
        ax = plt.gca()
        h = self.exon_height
        y0 = y_center - h / 2.0
        grey = _UI_GREY

        # sort exons in genomic order wrt strand
        ex = [[min(a, b), max(a, b)] for a, b in exons_e_s]
        ex.sort(key=lambda e: e[0], reverse=(strand < 0))

        # intron connectors
        for i in range(len(ex) - 1):
            ax.plot([mapper(ex[i][1]), mapper(ex[i + 1][0])],
                    [y_center, y_center], color=grey, lw=1, zorder=0)

        # exons (+ optional CDS/UTR split)
        if cds_bounds is None:
            for s, e in ex:
                xs, xe = mapper(s), mapper(e)
                ax.add_patch(Rectangle((xs, y0), xe - xs, h, fc=color, ec='black', zorder=1))
        else:
            cs, ce = sorted(cds_bounds)
            utr_h = h * 0.60
            utr_y = y_center - utr_h / 2.0
            for s, e in ex:
                if s < cs:
                    xs, xe = mapper(s), mapper(min(e, cs))
                    if xe > xs:
                        ax.add_patch(Rectangle((xs, utr_y), xe - xs, utr_h, fc=color, ec='black', zorder=1))
                c0, c1 = max(s, cs), min(e, ce)
                if c0 < c1:
                    xs, xe = mapper(c0), mapper(c1)
                    ax.add_patch(Rectangle((xs, y0), xe - xs, h, fc=color, ec='black', zorder=1))
                if e > ce:
                    xs, xe = mapper(max(s, ce)), mapper(e)
                    if xe > xs:
                        ax.add_patch(Rectangle((xs, utr_y), xe - xs, utr_h, fc=color, ec='black', zorder=1))

        # direction arrow
        arrow_y = y0 - 0.10 * h
        if strand > 0:
            ax.arrow(0, arrow_y, 1, 0, width=0.0015, head_length=0.01, head_width=0.10,
                     length_includes_head=True, overhang=1, color=grey)
        else:
            ax.arrow(1, arrow_y, -1, 0, width=0.0015, head_length=0.01, head_width=0.10,
                     length_includes_head=True, overhang=1, color=grey)

        # per-row boundary ticks (optional)
        if show_row_bounds:
            real_start = ex[0][0] if strand == 1 else ex[-1][1]
            real_end = ex[-1][1] if strand == 1 else ex[0][0]
            s_scaled, e_scaled = mapper(real_start), mapper(real_end)
            ax.plot([s_scaled, s_scaled], [arrow_y - 0.03, arrow_y + 0.03], color=grey)
            ax.plot([e_scaled, e_scaled], [arrow_y - 0.03, arrow_y + 0.03], color=grey)

        # transcript label (right-aligned under the row)
        label_y = y_center - h * (0.9 + self.label_drop)
        ax.text(0.995, label_y, tid_label, ha='right', va='top', fontsize=12)

        # length bar
        if length_bar is not None:
            bx0, bx1 = length_bar["x0"], length_bar["x1"]
            frac = float(length_bar["frac"])
            length_txt = length_bar["label"]
            bar_w = (bx1 - bx0) * max(0.0, min(1.0, frac))
            bh = 0.030
            by = arrow_y - bh
            ax.add_patch(Rectangle((bx0, by), bar_w, bh, fc=grey, ec='none', alpha=0.65, zorder=0))
            ax.text(bx0 + bar_w + 0.006, by - 0.010, length_txt,
                    ha='left', va='top', fontsize=9, color=grey)
            
    def _draw_top_ruler(self, ax, mapper, g0: int, g1: int, yref: float,
                        contig: Optional[str], gene_label: str):
        grey = _UI_GREY
        ax.hlines(yref, 0.0, 1.0, lw=0.9, color=grey)
        x0, x1 = mapper(int(g0)), mapper(int(g1))
        ax.vlines(x0, yref - 0.02, yref + 0.02, lw=0.9, color=grey)
        ax.vlines(x1, yref - 0.02, yref + 0.02, lw=0.9, color=grey)
        ax.text(x0, yref + 0.03, f"{int(g0):,}", ha='center', va='bottom', fontsize=9, color=grey)
        ax.text(x1, yref + 0.03, f"{int(g1):,}", ha='center', va='bottom', fontsize=9, color=grey)
        if gene_label:
            mid_x = (x0 + x1) / 2
            ax.text(mid_x, yref + 0.10, gene_label,
                    ha='center', va='bottom', fontsize=13, fontweight='bold', color='black')
        span_kb = (int(g1) - int(g0) + 1) / 1e3
        mid_x = (x0 + x1) / 2
        center = (f"{contig}: {int(g0):,}–{int(g1):,} ({span_kb:.1f} kb)" if contig
                  else f"{int(g0):,}–{int(g1):,} ({span_kb:.1f} kb)")
        ax.text(mid_x, yref - 0.04, center, ha='center', va='top', fontsize=10, color=grey)

    # ---------------- helpers used by public methods ----------------
    def _layout_and_mapper(self, transcripts_ids, *, draw_cds=False):
        tids = [self._versionless(t) for t in transcripts_ids]
        exons_list, strands, cds_map, exonic_len, genomic_span = [], [], {}, [], []
        for tid in tids:
            exs, st = self._get_exons_and_strand(tid)
            exons_list.append(exs); strands.append(st)
            cds_map[tid] = self._get_cds_bounds(tid) if draw_cds else None
            exonic_len.append(sum(abs(b - a) for a, b in exs))
            starts = [min(a, b) for a, b in exs]; ends = [max(a, b) for a, b in exs]
            genomic_span.append(max(ends) - min(starts))
        f, (g0, g1) = self._make_global_mapping(exons_list)
        # Pre-cache key genomic positions
        uniq = set()
        for tid, exs in zip(tids, exons_list):
            for a, b in exs:
                s, e = (min(a, b), max(a, b))
                uniq.add(s); uniq.add(e)
            if cds_map[tid] is not None:
                cs, ce = cds_map[tid]; uniq.add(int(cs)); uniq.add(int(ce))
        cache = {g: f(g) for g in sorted(uniq)}
        mapper = lambda x: cache.setdefault(x, f(x))
        return tids, exons_list, strands, cds_map, mapper, (g0, g1), np.array(exonic_len), np.array(genomic_span)

    def _contig_from_transcripts(self, tids: list[str]) -> Optional[str]:
        info = self.transcript_data.get_transcript_info(self._versionless(tids[0]))
        for k in ("contig", "chrom", "seqname", "chromosome", "chr"):
            if k in info and info[k]:
                c = str(info[k])
                return c if c.startswith("chr") else f"chr{c}"
        return None

    def _gene_label_from_transcripts(self, tids: list[str]) -> str:
        td = self.transcript_data
        symbols, gene_ids = [], []
        for t in tids:
            info = td.get_transcript_info(self._versionless(t))
            for k in ("gene_name", "gene", "symbol", "gene_symbol", "Name"):
                if k in info and info[k]:
                    symbols.append(str(info[k])); break
            if "gene_id" in info and info["gene_id"]:
                gene_ids.append(str(info["gene_id"]))
        if symbols:
            # majority label
            s, n = np.unique(symbols, return_counts=True)
            return s[np.argmax(n)]
        if gene_ids:
            return gene_ids[0]
        return self._versionless(tids[0]) if tids else ""

    def _draw_column_labels(self, ax, x0, col_w, cell_gap, y_baseline, labels: list[str], *,
                            counts: list[int] | None, rotation: int, fontsize: int, wrap_chars: int):
        for j, lab in enumerate(labels):
            name_lines = self._soft_wrap(lab, width=wrap_chars, max_lines=3)
            x = x0 + j * (col_w + cell_gap) + col_w / 2
            y = y_baseline
            for k, line in enumerate(name_lines):
                ax.text(x, y - 0.015*k, line, ha="center", va="top", fontsize=fontsize, rotation=rotation)
            if counts is not None:
                ax.text(x, y - 0.015*len(name_lines) - 0.010, f"(n={counts[j]})",
                        ha="center", va="top", fontsize=max(7, fontsize-1), color="#555555", rotation=rotation)

    def _draw_column_color_band(self, ax, x0, col_w, cell_gap, y_top, ct_colors: list[str] | None):
        if not ct_colors:
            return
        band_h = 0.035
        for j, c in enumerate(ct_colors):
            if c is None:
                continue
            ax.add_patch(Rectangle((x0 + j*(col_w+cell_gap), y_top),
                                   col_w, band_h, facecolor=c, edgecolor='black',
                                   linewidth=0.4, zorder=3))

    # ---------------- public: base schematic ----------------
    def draw_transcripts_list(self, transcripts_ids: List[str], colors: Optional[List[str]] = None, *,
                              draw_cds: bool = False, show_ticks: bool = False,
                              show_row_bounds: bool = False, title_gene: Optional[str] = None):
        (tids, exons_list, strands, cds_map, mapper, (g0, g1), exonic_len, genomic_span) = \
            self._layout_and_mapper(transcripts_ids, draw_cds=draw_cds)
        fig, ax, ycs = self._prep_axes(len(tids), reserve_panel_space=False)

        C = colors or [self.colors[i % len(self.colors)] for i in range(len(tids))]
        L = exonic_len if self.length_mode == 'exonic' else genomic_span
        Lmax = float(max(L)) or 1.0

        for i, (y, tid, exs, st, co) in enumerate(zip(ycs, tids, exons_list, strands, C)):
            length_bar = None
            if self.show_length:
                frac = L[i] / Lmax; kb = L[i] / 1e3
                length_bar = {"x0": 0.02, "x1": 0.20, "frac": frac, "label": f"{kb:.1f} kb"}
            self._draw_one(exs, st, co, tid, mapper, y_center=y,
                           cds_bounds=cds_map[tid], show_row_bounds=show_row_bounds,
                           length_bar=length_bar)

        contig = self._contig_from_transcripts(tids)
        gene_label = title_gene or self._gene_label_from_transcripts(tids)
        if show_ticks:
            ytick = ycs[0] + self.exon_height
            self._draw_top_ruler(ax, mapper, g0, g1, yref=ytick,
                                 contig=contig, gene_label=gene_label)
        plt.show()

    # ---------------- public: heatmap inline (right panel) --------------
    def draw_transcripts_with_heatmap_inline(
        self, transcripts_ids: list[str], values: np.ndarray,
        col_labels: Optional[list[str]] = None, *,
        cmap: str = "rocket_r", vmin=None, vmax=None,
        draw_cds: bool = True, show_ticks: bool = True,
        # aesthetics / adaptability
        cell_height: float = 0.28, cell_gap: float = 0.02,
        min_col_w: float = 0.035, max_panel_w: float = 0.55,
        show_row_bounds: bool = False, title_gene: Optional[str] = None,
        # optional cell-type colors (list aligned to columns, or dict label->color)
        ct_colors: Optional[Sequence[str] | dict] = None,
        # label controls
        force_rotation: Optional[int] = None,  # e.g. 35 or 45; None = auto
        wrap_chars_override: Optional[int] = None,
        show_counts_line: bool = True
    ):
        """
        Transcript schematic on the left + adaptive heatmap on the right.
        Robust labels (wrap/rotate/size), optional cell-type color band, tidy colorbar.
        """
        # ---------- left panel layout ----------
        (tids, exons_list, strands, cds_map, mapper, (g0, g1),
         exonic_len, genomic_span) = self._layout_and_mapper(transcripts_ids, draw_cds=draw_cds)

        # adapt right-panel width to number of columns
        n_cols = int(values.shape[1])
        needed_panel_w = n_cols * (min_col_w + cell_gap) - (cell_gap if n_cols > 0 else 0)
        self.panel_width = min(max_panel_w, max(0.22, needed_panel_w))

        fig, ax, ycs = self._prep_axes(len(tids), reserve_panel_space=True)

        # draw left rows
        L = exonic_len if self.length_mode == 'exonic' else genomic_span
        Lmax = float(max(L)) or 1.0
        C = [self.colors[i % len(self.colors)] for i in range(len(tids))]
        for i, (y, tid, exs, st, co) in enumerate(zip(ycs, tids, exons_list, strands, C)):
            length_bar = None
            if self.show_length:
                frac = L[i] / Lmax; kb = L[i] / 1e3
                length_bar = {"x0": 0.02, "x1": 0.20, "frac": frac, "label": f"{kb:.1f} kb"}
            self._draw_one(exs, st, co, tid, mapper, y_center=y,
                           cds_bounds=cds_map[tid], show_row_bounds=show_row_bounds,
                           length_bar=length_bar)

        contig = self._contig_from_transcripts(tids)
        gene_label = title_gene or self._gene_label_from_transcripts(tids)
        if show_ticks:
            ytick = ycs[0] + self.exon_height
            self._draw_top_ruler(ax, mapper, g0, g1, yref=ytick,
                                 contig=contig, gene_label=gene_label)

        # ---------- right panel geometry ----------
        x0 = self.panel_x0
        usable_w = self.panel_width
        m = n_cols
        col_w = (usable_w - (m - 1) * cell_gap) / max(1, m)

        # ---------- color mapping ----------
        cmap_obj = plt.get_cmap(cmap)
        if vmin is None or vmax is None:
            vmin = np.nanmin(values) if vmin is None else vmin
            vmax = np.nanmax(values) if vmax is None else vmax
        norm = mcolors.Normalize(vmin=vmin, vmax=vmax)

        # ---------- heatmap cells ----------
        for i, y in enumerate(ycs):
            y0_row = y - cell_height / 2.0
            for j in range(m):
                v = values[i, j]
                ax.add_patch(Rectangle((x0 + j * (col_w + cell_gap), y0_row),
                                       col_w, cell_height,
                                       facecolor=cmap_obj(norm(v)),
                                       edgecolor='black', linewidth=0.5, zorder=2))

        # ---------- optional column color band ----------
        resolved_ct_colors = None
        if ct_colors is not None:
            if isinstance(ct_colors, dict):
                lbls_for_colors = col_labels if col_labels else [f"C{j+1}" for j in range(m)]
                resolved_ct_colors = [ct_colors.get(l, None) for l in lbls_for_colors]
            else:
                resolved_ct_colors = list(ct_colors)
        y_top_band = self.top_margin + 0.02
        self._draw_column_color_band(ax, x0, col_w, cell_gap, y_top_band, resolved_ct_colors)

        # ---------- column labels (robust) ----------
        lbls = col_labels if col_labels else [f"C{j+1}" for j in range(m)]
        avg_chars = np.mean([len(s.split("\n")[0]) for s in lbls]) if lbls else 12
        rot, fs, wrap = self._fit_font_for_columns(m, usable_w, avg_chars,
                                                   min_fs=8, max_fs=11, rotate_threshold=9)
        if any(len(s.split("\n")[0]) > 16 for s in lbls) and force_rotation is None:
            rot = 35
        if force_rotation is not None:
            rot = int(force_rotation)
        if wrap_chars_override is not None:
            wrap = int(wrap_chars_override)

        # split out "(n=..)" from labels; optionally suppress counts line
        names_clean, counts = [], []
        for s in lbls:
            parts = s.split("\n")
            names_clean.append(parts[0])
            c = None
            for p in parts[1:]:
                m0 = re.search(r"\(n\s*=\s*(\d+)\)", p)
                if m0: c = int(m0.group(1)); break
            counts.append(c)
        if not show_counts_line or not any(c is not None for c in counts):
            counts = None

        label_y = ycs[-1] - self.row_pitch / 2 - (0.12 if rot else 0.08)
        self._draw_column_labels(ax, x0, col_w, cell_gap, label_y,
                                 names_clean, counts=counts,
                                 rotation=rot, fontsize=fs, wrap_chars=wrap)

        # ---------- compact colorbar ----------
        sm = plt.cm.ScalarMappable(cmap=cmap_obj, norm=norm); sm.set_array([])
        cbar = fig.colorbar(sm, ax=ax, fraction=0.05, pad=0.02,
                            shrink=0.9, aspect=22)
        locator = MaxNLocator(nbins=5, prune=None)
        cbar.locator = locator; cbar.update_ticks()
        if 0 <= vmin and vmax <= 100:
            cbar.ax.yaxis.set_major_formatter(FuncFormatter(lambda x, pos: f"{int(x)}"))
        else:
            cbar.ax.yaxis.set_major_formatter(FuncFormatter(lambda x, pos: f"{x:.2f}"))
        cbar.ax.tick_params(labelsize=9, length=3, width=0.6)
        cbar.set_label("Value", fontsize=10, labelpad=8,
                       rotation=270, va="center")

        # ---------- legend for cell-type colors (if provided) ----------
        if resolved_ct_colors and any(c is not None for c in resolved_ct_colors):
            uniq = []
            for name, col in zip(names_clean, resolved_ct_colors):
                if col is None: continue
                if not any(name == n and col == c for n, c in uniq):
                    uniq.append((name, col))
            if uniq:
                from matplotlib.lines import Line2D
                handles = [Line2D([0],[0], marker='s', linestyle='',
                                  markerfacecolor=col, markeredgecolor='black',
                                  markersize=8, label=name)
                           for name, col in uniq]
                ax.legend(handles=handles, title="Cell types", loc='upper left',
                          bbox_to_anchor=(x0+usable_w+0.02, 1.0),
                          borderaxespad=0., frameon=False,
                          fontsize=9, title_fontsize=9)

        plt.show()

    # ---------------- public: forest inline (right panel) ----------------
    def draw_transcripts_with_forest_inline(self, transcripts_ids: List[str], effects: np.ndarray,
                                            ci_low: Optional[np.ndarray] = None, ci_high: Optional[np.ndarray] = None,
                                            *, draw_cds: bool = True, show_ticks: bool = True,
                                            x_label: str = "Δ isoform usage", dot_size: float = 18,
                                            show_row_bounds: bool = False, title_gene: Optional[str] = None):
        (tids, exons_list, strands, cds_map, mapper, (g0, g1), exonic_len, genomic_span) = \
            self._layout_and_mapper(transcripts_ids, draw_cds=draw_cds)
        fig, ax, ycs = self._prep_axes(len(tids), reserve_panel_space=True)

        L = exonic_len if self.length_mode == 'exonic' else genomic_span
        Lmax = float(max(L)) or 1.0
        C = [self.colors[i % len(self.colors)] for i in range(len(tids))]
        for i, (y, tid, exs, st, co) in enumerate(zip(ycs, tids, exons_list, strands, C)):
            length_bar = None
            if self.show_length:
                frac = L[i] / Lmax; kb = L[i] / 1e3
                length_bar = {"x0": 0.02, "x1": 0.20, "frac": frac, "label": f"{kb:.1f} kb"}
            self._draw_one(exs, st, co, tid, mapper, y_center=y,
                           cds_bounds=cds_map[tid], show_row_bounds=show_row_bounds,
                           length_bar=length_bar)

        contig = self._contig_from_transcripts(tids)
        gene_label = title_gene or self._gene_label_from_transcripts(tids)
        if show_ticks:
            ytick = ycs[0] + self.exon_height
            self._draw_top_ruler(ax, mapper, g0, g1, yref=ytick,
                                 contig=contig, gene_label=gene_label)

        # map numeric values into right-panel width
        x0, x1 = self.panel_x0, self.panel_x0 + self.panel_width
        if ci_low is not None and ci_high is not None:
            xmin = float(np.nanmin(ci_low)); xmax = float(np.nanmax(ci_high))
        else:
            xmin = float(np.nanmin(effects)); xmax = float(np.nanmax(effects))
        span = xmax - xmin or 1.0
        X = lambda v: x0 + ((v - xmin) / span) * (x1 - x0)

        # zero reference line
        plt.plot([X(0.0), X(0.0)], [self.top_margin, ycs[-1] - self.row_pitch / 2],
                 color=_UI_GREY, lw=0.8, alpha=0.8)

        # CI + points
        for i, y in enumerate(ycs):
            if ci_low is not None and ci_high is not None:
                plt.plot([X(ci_low[i]), X(ci_high[i])], [y, y], color='black', lw=1.2, zorder=2)
            plt.scatter([X(effects[i])], [y], s=dot_size, color='black', zorder=3)

        # x-axis labels
        ticks = np.linspace(xmin, xmax, 3)
        label_y = ycs[-1] - self.row_pitch / 2 - 0.10
        for t in ticks:
            plt.text(X(t), label_y, f"{t:.2f}", ha='center', va='top', fontsize=10)
        plt.text((x0 + x1) / 2, label_y - 0.05, x_label, ha='center', va='top', fontsize=11)

        plt.show()




